%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.3

-ifndef(p10).
-define(p10, true).

-define(p10_gpb_version, "4.1.3").

-ifndef('CS_10004_PB_H').
-define('CS_10004_PB_H', true).
-record(cs_10004,
        {
        }).
-endif.

-ifndef('CS_10011_PB_H').
-define('CS_10011_PB_H', true).
-record(cs_10011,
        {resultData             :: binary()         % = 2
        }).
-endif.

-ifndef('CS_10010_PB_H').
-define('CS_10010_PB_H', true).
-record(cs_10010,
        {processData            :: binary()         % = 1
        }).
-endif.

-ifndef('CS_10000_PB_H').
-define('CS_10000_PB_H', true).
-record(cs_10000,
        {openId                 :: iolist(),        % = 1
         nickname               :: iolist(),        % = 2
         avatarUrl              :: iolist(),        % = 3
         sign                   :: iolist(),        % = 4
         timestamp              :: integer()        % = 5, 32 bits
        }).
-endif.

-ifndef('SC_10011_PB_H').
-define('SC_10011_PB_H', true).
-record(sc_10011,
        {playerId               :: integer(),       % = 1, 32 bits
         resultData             :: binary(),        % = 2
         seeds = []             :: [integer()] | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('SC_10001_PB_H').
-define('SC_10001_PB_H', true).
-record(sc_10001,
        {result                 :: integer(),       % = 1, 32 bits
         roomId                 :: integer(),       % = 2, 32 bits
         matchId                :: iolist()         % = 3
        }).
-endif.

-ifndef('CS_10002_PB_H').
-define('CS_10002_PB_H', true).
-record(cs_10002,
        {
        }).
-endif.

-ifndef('CS_10001_PB_H').
-define('CS_10001_PB_H', true).
-record(cs_10001,
        {matchId                :: iolist()         % = 1
        }).
-endif.

-ifndef('SC_10010_PB_H').
-define('SC_10010_PB_H', true).
-record(sc_10010,
        {playerId               :: integer(),       % = 1, 32 bits
         processData            :: binary()         % = 2
        }).
-endif.

-ifndef('SC_10002_PB_H').
-define('SC_10002_PB_H', true).
-record(sc_10002,
        {result                 :: integer()        % = 1, 32 bits
        }).
-endif.

-ifndef('SC_10003_PB_H').
-define('SC_10003_PB_H', true).
-record(sc_10003,
        {readyTime              :: integer()        % = 1, 32 bits
        }).
-endif.

-ifndef('SC_10000_PB_H').
-define('SC_10000_PB_H', true).
-record(sc_10000,
        {result                 :: integer(),       % = 1, 32 bits
         playerId               :: integer()        % = 2, 32 bits
        }).
-endif.

-endif.
