%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.3
-module(p11).

-export([encode_msg/1, encode_msg/2]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/2, merge_msgs/3]).
-export([verify_msg/1, verify_msg/2]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([get_package_name/0]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).

-include("p11.hrl").
-include("gpb.hrl").

%% enumerated types

-export_type([]).

%% message types
-type sc_11012() :: #sc_11012{}.
-type playerInfo() :: #playerInfo{}.
-type sc_11003() :: #sc_11003{}.
-type cs_11010() :: #cs_11010{}.
-type sc_11011() :: #sc_11011{}.
-type cs_11012() :: #cs_11012{}.
-type sc_11002() :: #sc_11002{}.
-type sc_11010() :: #sc_11010{}.
-type cs_11013() :: #cs_11013{}.
-type cs_11004() :: #cs_11004{}.
-type cs_11002() :: #cs_11002{}.
-type cs_11011() :: #cs_11011{}.
-export_type(['sc_11012'/0, 'playerInfo'/0, 'sc_11003'/0, 'cs_11010'/0, 'sc_11011'/0, 'cs_11012'/0, 'sc_11002'/0, 'sc_11010'/0, 'cs_11013'/0, 'cs_11004'/0, 'cs_11002'/0, 'cs_11011'/0]).

-spec encode_msg(#sc_11012{} | #playerInfo{} | #sc_11003{} | #cs_11010{} | #sc_11011{} | #cs_11012{} | #sc_11002{} | #sc_11010{} | #cs_11013{} | #cs_11004{} | #cs_11002{} | #cs_11011{}) -> binary().
encode_msg(Msg) -> encode_msg(Msg, []).


-spec encode_msg(#sc_11012{} | #playerInfo{} | #sc_11003{} | #cs_11010{} | #sc_11011{} | #cs_11012{} | #sc_11002{} | #sc_11010{} | #cs_11013{} | #cs_11004{} | #cs_11002{} | #cs_11011{}, list()) -> binary().
encode_msg(Msg, Opts) ->
    case proplists:get_bool(verify, Opts) of
      true -> verify_msg(Msg, Opts);
      false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case Msg of
      #sc_11012{} -> e_msg_sc_11012(Msg, TrUserData);
      #playerInfo{} -> e_msg_playerInfo(Msg, TrUserData);
      #sc_11003{} -> e_msg_sc_11003(Msg, TrUserData);
      #cs_11010{} -> e_msg_cs_11010(Msg, TrUserData);
      #sc_11011{} -> e_msg_sc_11011(Msg, TrUserData);
      #cs_11012{} -> e_msg_cs_11012(Msg, TrUserData);
      #sc_11002{} -> e_msg_sc_11002(Msg, TrUserData);
      #sc_11010{} -> e_msg_sc_11010(Msg, TrUserData);
      #cs_11013{} -> e_msg_cs_11013(Msg, TrUserData);
      #cs_11004{} -> e_msg_cs_11004(Msg, TrUserData);
      #cs_11002{} -> e_msg_cs_11002(Msg, TrUserData);
      #cs_11011{} -> e_msg_cs_11011(Msg, TrUserData)
    end.



e_msg_sc_11012(Msg, TrUserData) ->
    e_msg_sc_11012(Msg, <<>>, TrUserData).


e_msg_sc_11012(#sc_11012{result = F1, winPlayerId = F2},
	       Bin, TrUserData) ->
    B1 = begin
	   TrF1 = id(F1, TrUserData),
	   e_type_int32(TrF1, <<Bin/binary, 8>>)
	 end,
    begin
      TrF2 = id(F2, TrUserData),
      e_type_int64(TrF2, <<B1/binary, 16>>)
    end.

e_msg_playerInfo(Msg, TrUserData) ->
    e_msg_playerInfo(Msg, <<>>, TrUserData).


e_msg_playerInfo(#playerInfo{playerId = F1, openId = F2,
			     nickname = F3, avatarUrl = F4, isRobot = F5,
			     gender = F6, battleTimes = F7, robotLevel = F8},
		 Bin, TrUserData) ->
    B1 = begin
	   TrF1 = id(F1, TrUserData),
	   e_type_int64(TrF1, <<Bin/binary, 8>>)
	 end,
    B2 = begin
	   TrF2 = id(F2, TrUserData),
	   e_type_string(TrF2, <<B1/binary, 18>>)
	 end,
    B3 = begin
	   TrF3 = id(F3, TrUserData),
	   e_type_string(TrF3, <<B2/binary, 26>>)
	 end,
    B4 = begin
	   TrF4 = id(F4, TrUserData),
	   e_type_string(TrF4, <<B3/binary, 34>>)
	 end,
    B5 = begin
	   TrF5 = id(F5, TrUserData),
	   e_type_int32(TrF5, <<B4/binary, 40>>)
	 end,
    B6 = begin
	   TrF6 = id(F6, TrUserData),
	   e_type_int32(TrF6, <<B5/binary, 48>>)
	 end,
    B7 = if F7 == undefined -> B6;
	    true ->
		begin
		  TrF7 = id(F7, TrUserData),
		  e_type_int32(TrF7, <<B6/binary, 56>>)
		end
	 end,
    if F8 == undefined -> B7;
       true ->
	   begin
	     TrF8 = id(F8, TrUserData),
	     e_type_int32(TrF8, <<B7/binary, 64>>)
	   end
    end.

e_msg_sc_11003(Msg, TrUserData) ->
    e_msg_sc_11003(Msg, <<>>, TrUserData).


e_msg_sc_11003(#sc_11003{readyTime = F1,
			 playerInfos = F2},
	       Bin, TrUserData) ->
    B1 = begin
	   TrF1 = id(F1, TrUserData),
	   e_type_int32(TrF1, <<Bin/binary, 8>>)
	 end,
    begin
      TrF2 = id(F2, TrUserData),
      if TrF2 == [] -> B1;
	 true ->
	     e_field_sc_11003_playerInfos(TrF2, B1, TrUserData)
      end
    end.

e_msg_cs_11010(Msg, TrUserData) ->
    e_msg_cs_11010(Msg, <<>>, TrUserData).


e_msg_cs_11010(#cs_11010{processData = F1}, Bin,
	       TrUserData) ->
    begin
      TrF1 = id(F1, TrUserData),
      e_type_bytes(TrF1, <<Bin/binary, 10>>)
    end.

e_msg_sc_11011(Msg, TrUserData) ->
    e_msg_sc_11011(Msg, <<>>, TrUserData).


e_msg_sc_11011(#sc_11011{playerId = F1,
			 playerScore = F2, resultData = F3, seeds = F4},
	       Bin, TrUserData) ->
    B1 = begin
	   TrF1 = id(F1, TrUserData),
	   e_type_int64(TrF1, <<Bin/binary, 8>>)
	 end,
    B2 = begin
	   TrF2 = id(F2, TrUserData),
	   e_type_int32(TrF2, <<B1/binary, 16>>)
	 end,
    B3 = begin
	   TrF3 = id(F3, TrUserData),
	   e_type_bytes(TrF3, <<B2/binary, 26>>)
	 end,
    begin
      TrF4 = id(F4, TrUserData),
      if TrF4 == [] -> B3;
	 true -> e_field_sc_11011_seeds(TrF4, B3, TrUserData)
      end
    end.

e_msg_cs_11012(Msg, TrUserData) ->
    e_msg_cs_11012(Msg, <<>>, TrUserData).


e_msg_cs_11012(#cs_11012{winPlayerId = F1}, Bin,
	       TrUserData) ->
    begin
      TrF1 = id(F1, TrUserData),
      e_type_int64(TrF1, <<Bin/binary, 8>>)
    end.

e_msg_sc_11002(Msg, TrUserData) ->
    e_msg_sc_11002(Msg, <<>>, TrUserData).


e_msg_sc_11002(#sc_11002{result = F1, playerId = F2,
			 openId = F3, seeds = F4},
	       Bin, TrUserData) ->
    B1 = begin
	   TrF1 = id(F1, TrUserData),
	   e_type_int32(TrF1, <<Bin/binary, 8>>)
	 end,
    B2 = begin
	   TrF2 = id(F2, TrUserData),
	   e_type_int64(TrF2, <<B1/binary, 16>>)
	 end,
    B3 = begin
	   TrF3 = id(F3, TrUserData),
	   e_type_string(TrF3, <<B2/binary, 26>>)
	 end,
    begin
      TrF4 = id(F4, TrUserData),
      if TrF4 == [] -> B3;
	 true -> e_field_sc_11002_seeds(TrF4, B3, TrUserData)
      end
    end.

e_msg_sc_11010(Msg, TrUserData) ->
    e_msg_sc_11010(Msg, <<>>, TrUserData).


e_msg_sc_11010(#sc_11010{playerId = F1,
			 processData = F2},
	       Bin, TrUserData) ->
    B1 = begin
	   TrF1 = id(F1, TrUserData),
	   e_type_int64(TrF1, <<Bin/binary, 8>>)
	 end,
    begin
      TrF2 = id(F2, TrUserData),
      e_type_bytes(TrF2, <<B1/binary, 18>>)
    end.

e_msg_cs_11013(_Msg, _TrUserData) -> <<>>.

e_msg_cs_11004(_Msg, _TrUserData) -> <<>>.

e_msg_cs_11002(_Msg, _TrUserData) -> <<>>.

e_msg_cs_11011(Msg, TrUserData) ->
    e_msg_cs_11011(Msg, <<>>, TrUserData).


e_msg_cs_11011(#cs_11011{playerScore = F1,
			 resultData = F2, level = F3, score2 = F4},
	       Bin, TrUserData) ->
    B1 = begin
	   TrF1 = id(F1, TrUserData),
	   e_type_int32(TrF1, <<Bin/binary, 8>>)
	 end,
    B2 = begin
	   TrF2 = id(F2, TrUserData),
	   e_type_bytes(TrF2, <<B1/binary, 18>>)
	 end,
    B3 = if F3 == undefined -> B2;
	    true ->
		begin
		  TrF3 = id(F3, TrUserData),
		  e_type_int32(TrF3, <<B2/binary, 24>>)
		end
	 end,
    if F4 == undefined -> B3;
       true ->
	   begin
	     TrF4 = id(F4, TrUserData),
	     e_type_int32(TrF4, <<B3/binary, 32>>)
	   end
    end.

e_mfield_sc_11003_playerInfos(Msg, Bin, TrUserData) ->
    SubBin = e_msg_playerInfo(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_sc_11003_playerInfos([Elem | Rest], Bin,
			     TrUserData) ->
    Bin2 = <<Bin/binary, 18>>,
    Bin3 = e_mfield_sc_11003_playerInfos(id(Elem,
					    TrUserData),
					 Bin2, TrUserData),
    e_field_sc_11003_playerInfos(Rest, Bin3, TrUserData);
e_field_sc_11003_playerInfos([], Bin, _TrUserData) ->
    Bin.

e_field_sc_11011_seeds([Elem | Rest], Bin,
		       TrUserData) ->
    Bin2 = <<Bin/binary, 32>>,
    Bin3 = e_type_int32(id(Elem, TrUserData), Bin2),
    e_field_sc_11011_seeds(Rest, Bin3, TrUserData);
e_field_sc_11011_seeds([], Bin, _TrUserData) -> Bin.

e_field_sc_11002_seeds([Elem | Rest], Bin,
		       TrUserData) ->
    Bin2 = <<Bin/binary, 32>>,
    Bin3 = e_type_int32(id(Elem, TrUserData), Bin2),
    e_field_sc_11002_seeds(Rest, Bin3, TrUserData);
e_field_sc_11002_seeds([], Bin, _TrUserData) -> Bin.

e_type_int32(Value, Bin)
    when 0 =< Value, Value =< 127 ->
    <<Bin/binary, Value>>;
e_type_int32(Value, Bin) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

e_type_int64(Value, Bin)
    when 0 =< Value, Value =< 127 ->
    <<Bin/binary, Value>>;
e_type_int64(Value, Bin) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

e_type_string(S, Bin) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

e_type_bytes(Bytes, Bin) when is_binary(Bytes) ->
    Bin2 = e_varint(byte_size(Bytes), Bin),
    <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin) when is_list(Bytes) ->
    BytesBin = iolist_to_binary(Bytes),
    Bin2 = e_varint(byte_size(BytesBin), Bin),
    <<Bin2/binary, BytesBin/binary>>.

e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).


decode_msg(Bin, MsgName) when is_binary(Bin) ->
    decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      sc_11012 ->
	  try d_msg_sc_11012(Bin, TrUserData) catch
	    Class:Reason ->
		StackTrace = erlang:get_stacktrace(),
		error({gpb_error,
		       {decoding_failure,
			{Bin, sc_11012, {Class, Reason, StackTrace}}}})
	  end;
      playerInfo ->
	  try d_msg_playerInfo(Bin, TrUserData) catch
	    Class:Reason ->
		StackTrace = erlang:get_stacktrace(),
		error({gpb_error,
		       {decoding_failure,
			{Bin, playerInfo, {Class, Reason, StackTrace}}}})
	  end;
      sc_11003 ->
	  try d_msg_sc_11003(Bin, TrUserData) catch
	    Class:Reason ->
		StackTrace = erlang:get_stacktrace(),
		error({gpb_error,
		       {decoding_failure,
			{Bin, sc_11003, {Class, Reason, StackTrace}}}})
	  end;
      cs_11010 ->
	  try d_msg_cs_11010(Bin, TrUserData) catch
	    Class:Reason ->
		StackTrace = erlang:get_stacktrace(),
		error({gpb_error,
		       {decoding_failure,
			{Bin, cs_11010, {Class, Reason, StackTrace}}}})
	  end;
      sc_11011 ->
	  try d_msg_sc_11011(Bin, TrUserData) catch
	    Class:Reason ->
		StackTrace = erlang:get_stacktrace(),
		error({gpb_error,
		       {decoding_failure,
			{Bin, sc_11011, {Class, Reason, StackTrace}}}})
	  end;
      cs_11012 ->
	  try d_msg_cs_11012(Bin, TrUserData) catch
	    Class:Reason ->
		StackTrace = erlang:get_stacktrace(),
		error({gpb_error,
		       {decoding_failure,
			{Bin, cs_11012, {Class, Reason, StackTrace}}}})
	  end;
      sc_11002 ->
	  try d_msg_sc_11002(Bin, TrUserData) catch
	    Class:Reason ->
		StackTrace = erlang:get_stacktrace(),
		error({gpb_error,
		       {decoding_failure,
			{Bin, sc_11002, {Class, Reason, StackTrace}}}})
	  end;
      sc_11010 ->
	  try d_msg_sc_11010(Bin, TrUserData) catch
	    Class:Reason ->
		StackTrace = erlang:get_stacktrace(),
		error({gpb_error,
		       {decoding_failure,
			{Bin, sc_11010, {Class, Reason, StackTrace}}}})
	  end;
      cs_11013 ->
	  try d_msg_cs_11013(Bin, TrUserData) catch
	    Class:Reason ->
		StackTrace = erlang:get_stacktrace(),
		error({gpb_error,
		       {decoding_failure,
			{Bin, cs_11013, {Class, Reason, StackTrace}}}})
	  end;
      cs_11004 ->
	  try d_msg_cs_11004(Bin, TrUserData) catch
	    Class:Reason ->
		StackTrace = erlang:get_stacktrace(),
		error({gpb_error,
		       {decoding_failure,
			{Bin, cs_11004, {Class, Reason, StackTrace}}}})
	  end;
      cs_11002 ->
	  try d_msg_cs_11002(Bin, TrUserData) catch
	    Class:Reason ->
		StackTrace = erlang:get_stacktrace(),
		error({gpb_error,
		       {decoding_failure,
			{Bin, cs_11002, {Class, Reason, StackTrace}}}})
	  end;
      cs_11011 ->
	  try d_msg_cs_11011(Bin, TrUserData) catch
	    Class:Reason ->
		StackTrace = erlang:get_stacktrace(),
		error({gpb_error,
		       {decoding_failure,
			{Bin, cs_11011, {Class, Reason, StackTrace}}}})
	  end
    end.



d_msg_sc_11012(Bin, TrUserData) ->
    dfp_read_field_def_sc_11012(Bin, 0, 0,
				id(undefined, TrUserData),
				id(undefined, TrUserData), TrUserData).

dfp_read_field_def_sc_11012(<<8, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, TrUserData) ->
    d_field_sc_11012_result(Rest, Z1, Z2, F@_1, F@_2,
			    TrUserData);
dfp_read_field_def_sc_11012(<<16, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, TrUserData) ->
    d_field_sc_11012_winPlayerId(Rest, Z1, Z2, F@_1, F@_2,
				 TrUserData);
dfp_read_field_def_sc_11012(<<>>, 0, 0, F@_1, F@_2,
			    _) ->
    #sc_11012{result = F@_1, winPlayerId = F@_2};
dfp_read_field_def_sc_11012(Other, Z1, Z2, F@_1, F@_2,
			    TrUserData) ->
    dg_read_field_def_sc_11012(Other, Z1, Z2, F@_1, F@_2,
			       TrUserData).

dg_read_field_def_sc_11012(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_sc_11012(Rest, N + 7, X bsl N + Acc,
			       F@_1, F@_2, TrUserData);
dg_read_field_def_sc_11012(<<0:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 ->
	  d_field_sc_11012_result(Rest, 0, 0, F@_1, F@_2,
				  TrUserData);
      16 ->
	  d_field_sc_11012_winPlayerId(Rest, 0, 0, F@_1, F@_2,
				       TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_sc_11012(Rest, 0, 0, F@_1, F@_2,
				     TrUserData);
	    1 ->
		skip_64_sc_11012(Rest, 0, 0, F@_1, F@_2, TrUserData);
	    2 ->
		skip_length_delimited_sc_11012(Rest, 0, 0, F@_1, F@_2,
					       TrUserData);
	    3 ->
		skip_group_sc_11012(Rest, Key bsr 3, 0, F@_1, F@_2,
				    TrUserData);
	    5 ->
		skip_32_sc_11012(Rest, 0, 0, F@_1, F@_2, TrUserData)
	  end
    end;
dg_read_field_def_sc_11012(<<>>, 0, 0, F@_1, F@_2, _) ->
    #sc_11012{result = F@_1, winPlayerId = F@_2}.

d_field_sc_11012_result(<<1:1, X:7, Rest/binary>>, N,
			Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_sc_11012_result(Rest, N + 7, X bsl N + Acc,
			    F@_1, F@_2, TrUserData);
d_field_sc_11012_result(<<0:1, X:7, Rest/binary>>, N,
			Acc, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    Res
			  end,
			  Rest},
    dfp_read_field_def_sc_11012(RestF, 0, 0, NewFValue,
				F@_2, TrUserData).

d_field_sc_11012_winPlayerId(<<1:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_sc_11012_winPlayerId(Rest, N + 7, X bsl N + Acc,
				 F@_1, F@_2, TrUserData);
d_field_sc_11012_winPlayerId(<<0:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:64/signed-native>> = <<(X bsl N +
							    Acc):64/unsigned-native>>,
			    Res
			  end,
			  Rest},
    dfp_read_field_def_sc_11012(RestF, 0, 0, F@_1,
				NewFValue, TrUserData).

skip_varint_sc_11012(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, TrUserData) ->
    skip_varint_sc_11012(Rest, Z1, Z2, F@_1, F@_2,
			 TrUserData);
skip_varint_sc_11012(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, TrUserData) ->
    dfp_read_field_def_sc_11012(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

skip_length_delimited_sc_11012(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    skip_length_delimited_sc_11012(Rest, N + 7,
				   X bsl N + Acc, F@_1, F@_2, TrUserData);
skip_length_delimited_sc_11012(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_sc_11012(Rest2, 0, 0, F@_1, F@_2,
				TrUserData).

skip_group_sc_11012(Bin, FNum, Z2, F@_1, F@_2,
		    TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_sc_11012(Rest, 0, Z2, F@_1, F@_2,
				TrUserData).

skip_32_sc_11012(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, TrUserData) ->
    dfp_read_field_def_sc_11012(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

skip_64_sc_11012(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, TrUserData) ->
    dfp_read_field_def_sc_11012(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

d_msg_playerInfo(Bin, TrUserData) ->
    dfp_read_field_def_playerInfo(Bin, 0, 0,
				  id(undefined, TrUserData),
				  id(undefined, TrUserData),
				  id(undefined, TrUserData),
				  id(undefined, TrUserData),
				  id(undefined, TrUserData),
				  id(undefined, TrUserData),
				  id(undefined, TrUserData),
				  id(undefined, TrUserData), TrUserData).

dfp_read_field_def_playerInfo(<<8, Rest/binary>>, Z1,
			      Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7,
			      F@_8, TrUserData) ->
    d_field_playerInfo_playerId(Rest, Z1, Z2, F@_1, F@_2,
				F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
dfp_read_field_def_playerInfo(<<18, Rest/binary>>, Z1,
			      Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7,
			      F@_8, TrUserData) ->
    d_field_playerInfo_openId(Rest, Z1, Z2, F@_1, F@_2,
			      F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
dfp_read_field_def_playerInfo(<<26, Rest/binary>>, Z1,
			      Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7,
			      F@_8, TrUserData) ->
    d_field_playerInfo_nickname(Rest, Z1, Z2, F@_1, F@_2,
				F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
dfp_read_field_def_playerInfo(<<34, Rest/binary>>, Z1,
			      Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7,
			      F@_8, TrUserData) ->
    d_field_playerInfo_avatarUrl(Rest, Z1, Z2, F@_1, F@_2,
				 F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
				 TrUserData);
dfp_read_field_def_playerInfo(<<40, Rest/binary>>, Z1,
			      Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7,
			      F@_8, TrUserData) ->
    d_field_playerInfo_isRobot(Rest, Z1, Z2, F@_1, F@_2,
			       F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
dfp_read_field_def_playerInfo(<<48, Rest/binary>>, Z1,
			      Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7,
			      F@_8, TrUserData) ->
    d_field_playerInfo_gender(Rest, Z1, Z2, F@_1, F@_2,
			      F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
dfp_read_field_def_playerInfo(<<56, Rest/binary>>, Z1,
			      Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7,
			      F@_8, TrUserData) ->
    d_field_playerInfo_battleTimes(Rest, Z1, Z2, F@_1, F@_2,
				   F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
				   TrUserData);
dfp_read_field_def_playerInfo(<<64, Rest/binary>>, Z1,
			      Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7,
			      F@_8, TrUserData) ->
    d_field_playerInfo_robotLevel(Rest, Z1, Z2, F@_1, F@_2,
				  F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
				  TrUserData);
dfp_read_field_def_playerInfo(<<>>, 0, 0, F@_1, F@_2,
			      F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, _) ->
    #playerInfo{playerId = F@_1, openId = F@_2,
		nickname = F@_3, avatarUrl = F@_4, isRobot = F@_5,
		gender = F@_6, battleTimes = F@_7, robotLevel = F@_8};
dfp_read_field_def_playerInfo(Other, Z1, Z2, F@_1, F@_2,
			      F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) ->
    dg_read_field_def_playerInfo(Other, Z1, Z2, F@_1, F@_2,
				 F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
				 TrUserData).

dg_read_field_def_playerInfo(<<1:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7,
			     F@_8, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_playerInfo(Rest, N + 7, X bsl N + Acc,
				 F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
				 TrUserData);
dg_read_field_def_playerInfo(<<0:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7,
			     F@_8, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 ->
	  d_field_playerInfo_playerId(Rest, 0, 0, F@_1, F@_2,
				      F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
				      TrUserData);
      18 ->
	  d_field_playerInfo_openId(Rest, 0, 0, F@_1, F@_2, F@_3,
				    F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
      26 ->
	  d_field_playerInfo_nickname(Rest, 0, 0, F@_1, F@_2,
				      F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
				      TrUserData);
      34 ->
	  d_field_playerInfo_avatarUrl(Rest, 0, 0, F@_1, F@_2,
				       F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
				       TrUserData);
      40 ->
	  d_field_playerInfo_isRobot(Rest, 0, 0, F@_1, F@_2, F@_3,
				     F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
      48 ->
	  d_field_playerInfo_gender(Rest, 0, 0, F@_1, F@_2, F@_3,
				    F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
      56 ->
	  d_field_playerInfo_battleTimes(Rest, 0, 0, F@_1, F@_2,
					 F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
					 TrUserData);
      64 ->
	  d_field_playerInfo_robotLevel(Rest, 0, 0, F@_1, F@_2,
					F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
					TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_playerInfo(Rest, 0, 0, F@_1, F@_2, F@_3,
				       F@_4, F@_5, F@_6, F@_7, F@_8,
				       TrUserData);
	    1 ->
		skip_64_playerInfo(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4,
				   F@_5, F@_6, F@_7, F@_8, TrUserData);
	    2 ->
		skip_length_delimited_playerInfo(Rest, 0, 0, F@_1, F@_2,
						 F@_3, F@_4, F@_5, F@_6, F@_7,
						 F@_8, TrUserData);
	    3 ->
		skip_group_playerInfo(Rest, Key bsr 3, 0, F@_1, F@_2,
				      F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
				      TrUserData);
	    5 ->
		skip_32_playerInfo(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4,
				   F@_5, F@_6, F@_7, F@_8, TrUserData)
	  end
    end;
dg_read_field_def_playerInfo(<<>>, 0, 0, F@_1, F@_2,
			     F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, _) ->
    #playerInfo{playerId = F@_1, openId = F@_2,
		nickname = F@_3, avatarUrl = F@_4, isRobot = F@_5,
		gender = F@_6, battleTimes = F@_7, robotLevel = F@_8}.

d_field_playerInfo_playerId(<<1:1, X:7, Rest/binary>>,
			    N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7,
			    F@_8, TrUserData)
    when N < 57 ->
    d_field_playerInfo_playerId(Rest, N + 7, X bsl N + Acc,
				F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
				TrUserData);
d_field_playerInfo_playerId(<<0:1, X:7, Rest/binary>>,
			    N, Acc, _, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
			    TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:64/signed-native>> = <<(X bsl N +
							    Acc):64/unsigned-native>>,
			    Res
			  end,
			  Rest},
    dfp_read_field_def_playerInfo(RestF, 0, 0, NewFValue,
				  F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
				  TrUserData).

d_field_playerInfo_openId(<<1:1, X:7, Rest/binary>>, N,
			  Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
			  TrUserData)
    when N < 57 ->
    d_field_playerInfo_openId(Rest, N + 7, X bsl N + Acc,
			      F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
			      TrUserData);
d_field_playerInfo_openId(<<0:1, X:7, Rest/binary>>, N,
			  Acc, F@_1, _, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
			  TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Utf8:Len/binary, Rest2/binary>> = Rest,
			   {unicode:characters_to_list(Utf8, unicode), Rest2}
			 end,
    dfp_read_field_def_playerInfo(RestF, 0, 0, F@_1,
				  NewFValue, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
				  TrUserData).

d_field_playerInfo_nickname(<<1:1, X:7, Rest/binary>>,
			    N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7,
			    F@_8, TrUserData)
    when N < 57 ->
    d_field_playerInfo_nickname(Rest, N + 7, X bsl N + Acc,
				F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
				TrUserData);
d_field_playerInfo_nickname(<<0:1, X:7, Rest/binary>>,
			    N, Acc, F@_1, F@_2, _, F@_4, F@_5, F@_6, F@_7, F@_8,
			    TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Utf8:Len/binary, Rest2/binary>> = Rest,
			   {unicode:characters_to_list(Utf8, unicode), Rest2}
			 end,
    dfp_read_field_def_playerInfo(RestF, 0, 0, F@_1, F@_2,
				  NewFValue, F@_4, F@_5, F@_6, F@_7, F@_8,
				  TrUserData).

d_field_playerInfo_avatarUrl(<<1:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7,
			     F@_8, TrUserData)
    when N < 57 ->
    d_field_playerInfo_avatarUrl(Rest, N + 7, X bsl N + Acc,
				 F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
				 TrUserData);
d_field_playerInfo_avatarUrl(<<0:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, F@_2, F@_3, _, F@_5, F@_6, F@_7,
			     F@_8, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Utf8:Len/binary, Rest2/binary>> = Rest,
			   {unicode:characters_to_list(Utf8, unicode), Rest2}
			 end,
    dfp_read_field_def_playerInfo(RestF, 0, 0, F@_1, F@_2,
				  F@_3, NewFValue, F@_5, F@_6, F@_7, F@_8,
				  TrUserData).

d_field_playerInfo_isRobot(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
			   TrUserData)
    when N < 57 ->
    d_field_playerInfo_isRobot(Rest, N + 7, X bsl N + Acc,
			       F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
			       TrUserData);
d_field_playerInfo_isRobot(<<0:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, F@_3, F@_4, _, F@_6, F@_7, F@_8,
			   TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    Res
			  end,
			  Rest},
    dfp_read_field_def_playerInfo(RestF, 0, 0, F@_1, F@_2,
				  F@_3, F@_4, NewFValue, F@_6, F@_7, F@_8,
				  TrUserData).

d_field_playerInfo_gender(<<1:1, X:7, Rest/binary>>, N,
			  Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
			  TrUserData)
    when N < 57 ->
    d_field_playerInfo_gender(Rest, N + 7, X bsl N + Acc,
			      F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
			      TrUserData);
d_field_playerInfo_gender(<<0:1, X:7, Rest/binary>>, N,
			  Acc, F@_1, F@_2, F@_3, F@_4, F@_5, _, F@_7, F@_8,
			  TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    Res
			  end,
			  Rest},
    dfp_read_field_def_playerInfo(RestF, 0, 0, F@_1, F@_2,
				  F@_3, F@_4, F@_5, NewFValue, F@_7, F@_8,
				  TrUserData).

d_field_playerInfo_battleTimes(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7,
			       F@_8, TrUserData)
    when N < 57 ->
    d_field_playerInfo_battleTimes(Rest, N + 7,
				   X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5,
				   F@_6, F@_7, F@_8, TrUserData);
d_field_playerInfo_battleTimes(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, _,
			       F@_8, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    Res
			  end,
			  Rest},
    dfp_read_field_def_playerInfo(RestF, 0, 0, F@_1, F@_2,
				  F@_3, F@_4, F@_5, F@_6, NewFValue, F@_8,
				  TrUserData).

d_field_playerInfo_robotLevel(<<1:1, X:7, Rest/binary>>,
			      N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7,
			      F@_8, TrUserData)
    when N < 57 ->
    d_field_playerInfo_robotLevel(Rest, N + 7,
				  X bsl N + Acc, F@_1, F@_2, F@_3, F@_4, F@_5,
				  F@_6, F@_7, F@_8, TrUserData);
d_field_playerInfo_robotLevel(<<0:1, X:7, Rest/binary>>,
			      N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7,
			      _, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    Res
			  end,
			  Rest},
    dfp_read_field_def_playerInfo(RestF, 0, 0, F@_1, F@_2,
				  F@_3, F@_4, F@_5, F@_6, F@_7, NewFValue,
				  TrUserData).

skip_varint_playerInfo(<<1:1, _:7, Rest/binary>>, Z1,
		       Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
		       TrUserData) ->
    skip_varint_playerInfo(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			   F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
skip_varint_playerInfo(<<0:1, _:7, Rest/binary>>, Z1,
		       Z2, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
		       TrUserData) ->
    dfp_read_field_def_playerInfo(Rest, Z1, Z2, F@_1, F@_2,
				  F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
				  TrUserData).

skip_length_delimited_playerInfo(<<1:1, X:7,
				   Rest/binary>>,
				 N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6,
				 F@_7, F@_8, TrUserData)
    when N < 57 ->
    skip_length_delimited_playerInfo(Rest, N + 7,
				     X bsl N + Acc, F@_1, F@_2, F@_3, F@_4,
				     F@_5, F@_6, F@_7, F@_8, TrUserData);
skip_length_delimited_playerInfo(<<0:1, X:7,
				   Rest/binary>>,
				 N, Acc, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6,
				 F@_7, F@_8, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_playerInfo(Rest2, 0, 0, F@_1, F@_2,
				  F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
				  TrUserData).

skip_group_playerInfo(Bin, FNum, Z2, F@_1, F@_2, F@_3,
		      F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_playerInfo(Rest, 0, Z2, F@_1, F@_2,
				  F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
				  TrUserData).

skip_32_playerInfo(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		   F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) ->
    dfp_read_field_def_playerInfo(Rest, Z1, Z2, F@_1, F@_2,
				  F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
				  TrUserData).

skip_64_playerInfo(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		   F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) ->
    dfp_read_field_def_playerInfo(Rest, Z1, Z2, F@_1, F@_2,
				  F@_3, F@_4, F@_5, F@_6, F@_7, F@_8,
				  TrUserData).

d_msg_sc_11003(Bin, TrUserData) ->
    dfp_read_field_def_sc_11003(Bin, 0, 0,
				id(undefined, TrUserData), id([], TrUserData),
				TrUserData).

dfp_read_field_def_sc_11003(<<8, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, TrUserData) ->
    d_field_sc_11003_readyTime(Rest, Z1, Z2, F@_1, F@_2,
			       TrUserData);
dfp_read_field_def_sc_11003(<<18, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, TrUserData) ->
    d_field_sc_11003_playerInfos(Rest, Z1, Z2, F@_1, F@_2,
				 TrUserData);
dfp_read_field_def_sc_11003(<<>>, 0, 0, F@_1, R1,
			    TrUserData) ->
    #sc_11003{readyTime = F@_1,
	      playerInfos = lists_reverse(R1, TrUserData)};
dfp_read_field_def_sc_11003(Other, Z1, Z2, F@_1, F@_2,
			    TrUserData) ->
    dg_read_field_def_sc_11003(Other, Z1, Z2, F@_1, F@_2,
			       TrUserData).

dg_read_field_def_sc_11003(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_sc_11003(Rest, N + 7, X bsl N + Acc,
			       F@_1, F@_2, TrUserData);
dg_read_field_def_sc_11003(<<0:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 ->
	  d_field_sc_11003_readyTime(Rest, 0, 0, F@_1, F@_2,
				     TrUserData);
      18 ->
	  d_field_sc_11003_playerInfos(Rest, 0, 0, F@_1, F@_2,
				       TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_sc_11003(Rest, 0, 0, F@_1, F@_2,
				     TrUserData);
	    1 ->
		skip_64_sc_11003(Rest, 0, 0, F@_1, F@_2, TrUserData);
	    2 ->
		skip_length_delimited_sc_11003(Rest, 0, 0, F@_1, F@_2,
					       TrUserData);
	    3 ->
		skip_group_sc_11003(Rest, Key bsr 3, 0, F@_1, F@_2,
				    TrUserData);
	    5 ->
		skip_32_sc_11003(Rest, 0, 0, F@_1, F@_2, TrUserData)
	  end
    end;
dg_read_field_def_sc_11003(<<>>, 0, 0, F@_1, R1,
			   TrUserData) ->
    #sc_11003{readyTime = F@_1,
	      playerInfos = lists_reverse(R1, TrUserData)}.

d_field_sc_11003_readyTime(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_sc_11003_readyTime(Rest, N + 7, X bsl N + Acc,
			       F@_1, F@_2, TrUserData);
d_field_sc_11003_readyTime(<<0:1, X:7, Rest/binary>>, N,
			   Acc, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    Res
			  end,
			  Rest},
    dfp_read_field_def_sc_11003(RestF, 0, 0, NewFValue,
				F@_2, TrUserData).

d_field_sc_11003_playerInfos(<<1:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_sc_11003_playerInfos(Rest, N + 7, X bsl N + Acc,
				 F@_1, F@_2, TrUserData);
d_field_sc_11003_playerInfos(<<0:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, Prev, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Bs:Len/binary, Rest2/binary>> = Rest,
			   {id(d_msg_playerInfo(Bs, TrUserData), TrUserData),
			    Rest2}
			 end,
    dfp_read_field_def_sc_11003(RestF, 0, 0, F@_1,
				cons(NewFValue, Prev, TrUserData), TrUserData).

skip_varint_sc_11003(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, TrUserData) ->
    skip_varint_sc_11003(Rest, Z1, Z2, F@_1, F@_2,
			 TrUserData);
skip_varint_sc_11003(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, TrUserData) ->
    dfp_read_field_def_sc_11003(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

skip_length_delimited_sc_11003(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    skip_length_delimited_sc_11003(Rest, N + 7,
				   X bsl N + Acc, F@_1, F@_2, TrUserData);
skip_length_delimited_sc_11003(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_sc_11003(Rest2, 0, 0, F@_1, F@_2,
				TrUserData).

skip_group_sc_11003(Bin, FNum, Z2, F@_1, F@_2,
		    TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_sc_11003(Rest, 0, Z2, F@_1, F@_2,
				TrUserData).

skip_32_sc_11003(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, TrUserData) ->
    dfp_read_field_def_sc_11003(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

skip_64_sc_11003(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, TrUserData) ->
    dfp_read_field_def_sc_11003(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

d_msg_cs_11010(Bin, TrUserData) ->
    dfp_read_field_def_cs_11010(Bin, 0, 0,
				id(undefined, TrUserData), TrUserData).

dfp_read_field_def_cs_11010(<<10, Rest/binary>>, Z1, Z2,
			    F@_1, TrUserData) ->
    d_field_cs_11010_processData(Rest, Z1, Z2, F@_1,
				 TrUserData);
dfp_read_field_def_cs_11010(<<>>, 0, 0, F@_1, _) ->
    #cs_11010{processData = F@_1};
dfp_read_field_def_cs_11010(Other, Z1, Z2, F@_1,
			    TrUserData) ->
    dg_read_field_def_cs_11010(Other, Z1, Z2, F@_1,
			       TrUserData).

dg_read_field_def_cs_11010(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_cs_11010(Rest, N + 7, X bsl N + Acc,
			       F@_1, TrUserData);
dg_read_field_def_cs_11010(<<0:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_cs_11010_processData(Rest, 0, 0, F@_1,
				       TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_cs_11010(Rest, 0, 0, F@_1, TrUserData);
	    1 -> skip_64_cs_11010(Rest, 0, 0, F@_1, TrUserData);
	    2 ->
		skip_length_delimited_cs_11010(Rest, 0, 0, F@_1,
					       TrUserData);
	    3 ->
		skip_group_cs_11010(Rest, Key bsr 3, 0, F@_1,
				    TrUserData);
	    5 -> skip_32_cs_11010(Rest, 0, 0, F@_1, TrUserData)
	  end
    end;
dg_read_field_def_cs_11010(<<>>, 0, 0, F@_1, _) ->
    #cs_11010{processData = F@_1}.

d_field_cs_11010_processData(<<1:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, TrUserData)
    when N < 57 ->
    d_field_cs_11010_processData(Rest, N + 7, X bsl N + Acc,
				 F@_1, TrUserData);
d_field_cs_11010_processData(<<0:1, X:7, Rest/binary>>,
			     N, Acc, _, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Bytes:Len/binary, Rest2/binary>> = Rest,
			   {binary:copy(Bytes), Rest2}
			 end,
    dfp_read_field_def_cs_11010(RestF, 0, 0, NewFValue,
				TrUserData).

skip_varint_cs_11010(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, TrUserData) ->
    skip_varint_cs_11010(Rest, Z1, Z2, F@_1, TrUserData);
skip_varint_cs_11010(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, TrUserData) ->
    dfp_read_field_def_cs_11010(Rest, Z1, Z2, F@_1,
				TrUserData).

skip_length_delimited_cs_11010(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, TrUserData)
    when N < 57 ->
    skip_length_delimited_cs_11010(Rest, N + 7,
				   X bsl N + Acc, F@_1, TrUserData);
skip_length_delimited_cs_11010(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_cs_11010(Rest2, 0, 0, F@_1,
				TrUserData).

skip_group_cs_11010(Bin, FNum, Z2, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_cs_11010(Rest, 0, Z2, F@_1,
				TrUserData).

skip_32_cs_11010(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		 TrUserData) ->
    dfp_read_field_def_cs_11010(Rest, Z1, Z2, F@_1,
				TrUserData).

skip_64_cs_11010(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		 TrUserData) ->
    dfp_read_field_def_cs_11010(Rest, Z1, Z2, F@_1,
				TrUserData).

d_msg_sc_11011(Bin, TrUserData) ->
    dfp_read_field_def_sc_11011(Bin, 0, 0,
				id(undefined, TrUserData),
				id(undefined, TrUserData),
				id(undefined, TrUserData), id([], TrUserData),
				TrUserData).

dfp_read_field_def_sc_11011(<<8, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    d_field_sc_11011_playerId(Rest, Z1, Z2, F@_1, F@_2,
			      F@_3, F@_4, TrUserData);
dfp_read_field_def_sc_11011(<<16, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    d_field_sc_11011_playerScore(Rest, Z1, Z2, F@_1, F@_2,
				 F@_3, F@_4, TrUserData);
dfp_read_field_def_sc_11011(<<26, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    d_field_sc_11011_resultData(Rest, Z1, Z2, F@_1, F@_2,
				F@_3, F@_4, TrUserData);
dfp_read_field_def_sc_11011(<<34, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    d_pfield_sc_11011_seeds(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			    F@_4, TrUserData);
dfp_read_field_def_sc_11011(<<32, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    d_field_sc_11011_seeds(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			   F@_4, TrUserData);
dfp_read_field_def_sc_11011(<<>>, 0, 0, F@_1, F@_2,
			    F@_3, R1, TrUserData) ->
    #sc_11011{playerId = F@_1, playerScore = F@_2,
	      resultData = F@_3,
	      seeds = lists_reverse(R1, TrUserData)};
dfp_read_field_def_sc_11011(Other, Z1, Z2, F@_1, F@_2,
			    F@_3, F@_4, TrUserData) ->
    dg_read_field_def_sc_11011(Other, Z1, Z2, F@_1, F@_2,
			       F@_3, F@_4, TrUserData).

dg_read_field_def_sc_11011(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_sc_11011(Rest, N + 7, X bsl N + Acc,
			       F@_1, F@_2, F@_3, F@_4, TrUserData);
dg_read_field_def_sc_11011(<<0:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 ->
	  d_field_sc_11011_playerId(Rest, 0, 0, F@_1, F@_2, F@_3,
				    F@_4, TrUserData);
      16 ->
	  d_field_sc_11011_playerScore(Rest, 0, 0, F@_1, F@_2,
				       F@_3, F@_4, TrUserData);
      26 ->
	  d_field_sc_11011_resultData(Rest, 0, 0, F@_1, F@_2,
				      F@_3, F@_4, TrUserData);
      34 ->
	  d_pfield_sc_11011_seeds(Rest, 0, 0, F@_1, F@_2, F@_3,
				  F@_4, TrUserData);
      32 ->
	  d_field_sc_11011_seeds(Rest, 0, 0, F@_1, F@_2, F@_3,
				 F@_4, TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_sc_11011(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4,
				     TrUserData);
	    1 ->
		skip_64_sc_11011(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4,
				 TrUserData);
	    2 ->
		skip_length_delimited_sc_11011(Rest, 0, 0, F@_1, F@_2,
					       F@_3, F@_4, TrUserData);
	    3 ->
		skip_group_sc_11011(Rest, Key bsr 3, 0, F@_1, F@_2,
				    F@_3, F@_4, TrUserData);
	    5 ->
		skip_32_sc_11011(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4,
				 TrUserData)
	  end
    end;
dg_read_field_def_sc_11011(<<>>, 0, 0, F@_1, F@_2, F@_3,
			   R1, TrUserData) ->
    #sc_11011{playerId = F@_1, playerScore = F@_2,
	      resultData = F@_3,
	      seeds = lists_reverse(R1, TrUserData)}.

d_field_sc_11011_playerId(<<1:1, X:7, Rest/binary>>, N,
			  Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 57 ->
    d_field_sc_11011_playerId(Rest, N + 7, X bsl N + Acc,
			      F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_sc_11011_playerId(<<0:1, X:7, Rest/binary>>, N,
			  Acc, _, F@_2, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:64/signed-native>> = <<(X bsl N +
							    Acc):64/unsigned-native>>,
			    Res
			  end,
			  Rest},
    dfp_read_field_def_sc_11011(RestF, 0, 0, NewFValue,
				F@_2, F@_3, F@_4, TrUserData).

d_field_sc_11011_playerScore(<<1:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 57 ->
    d_field_sc_11011_playerScore(Rest, N + 7, X bsl N + Acc,
				 F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_sc_11011_playerScore(<<0:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, _, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    Res
			  end,
			  Rest},
    dfp_read_field_def_sc_11011(RestF, 0, 0, F@_1,
				NewFValue, F@_3, F@_4, TrUserData).

d_field_sc_11011_resultData(<<1:1, X:7, Rest/binary>>,
			    N, Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 57 ->
    d_field_sc_11011_resultData(Rest, N + 7, X bsl N + Acc,
				F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_sc_11011_resultData(<<0:1, X:7, Rest/binary>>,
			    N, Acc, F@_1, F@_2, _, F@_4, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Bytes:Len/binary, Rest2/binary>> = Rest,
			   {binary:copy(Bytes), Rest2}
			 end,
    dfp_read_field_def_sc_11011(RestF, 0, 0, F@_1, F@_2,
				NewFValue, F@_4, TrUserData).

d_field_sc_11011_seeds(<<1:1, X:7, Rest/binary>>, N,
		       Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 57 ->
    d_field_sc_11011_seeds(Rest, N + 7, X bsl N + Acc, F@_1,
			   F@_2, F@_3, F@_4, TrUserData);
d_field_sc_11011_seeds(<<0:1, X:7, Rest/binary>>, N,
		       Acc, F@_1, F@_2, F@_3, Prev, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    Res
			  end,
			  Rest},
    dfp_read_field_def_sc_11011(RestF, 0, 0, F@_1, F@_2,
				F@_3, cons(NewFValue, Prev, TrUserData),
				TrUserData).

d_pfield_sc_11011_seeds(<<1:1, X:7, Rest/binary>>, N,
			Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 57 ->
    d_pfield_sc_11011_seeds(Rest, N + 7, X bsl N + Acc,
			    F@_1, F@_2, F@_3, F@_4, TrUserData);
d_pfield_sc_11011_seeds(<<0:1, X:7, Rest/binary>>, N,
			Acc, F@_1, F@_2, F@_3, E, TrUserData) ->
    Len = X bsl N + Acc,
    <<PackedBytes:Len/binary, Rest2/binary>> = Rest,
    NewSeq = d_packed_field_sc_11011_seeds(PackedBytes, 0,
					   0, E),
    dfp_read_field_def_sc_11011(Rest2, 0, 0, F@_1, F@_2,
				F@_3, NewSeq, TrUserData).

d_packed_field_sc_11011_seeds(<<1:1, X:7, Rest/binary>>,
			      N, Acc, AccSeq)
    when N < 57 ->
    d_packed_field_sc_11011_seeds(Rest, N + 7,
				  X bsl N + Acc, AccSeq);
d_packed_field_sc_11011_seeds(<<0:1, X:7, Rest/binary>>,
			      N, Acc, AccSeq) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    Res
			  end,
			  Rest},
    d_packed_field_sc_11011_seeds(RestF, 0, 0,
				  [NewFValue | AccSeq]);
d_packed_field_sc_11011_seeds(<<>>, 0, 0, AccSeq) ->
    AccSeq.

skip_varint_sc_11011(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    skip_varint_sc_11011(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			 F@_4, TrUserData);
skip_varint_sc_11011(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    dfp_read_field_def_sc_11011(Rest, Z1, Z2, F@_1, F@_2,
				F@_3, F@_4, TrUserData).

skip_length_delimited_sc_11011(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 57 ->
    skip_length_delimited_sc_11011(Rest, N + 7,
				   X bsl N + Acc, F@_1, F@_2, F@_3, F@_4,
				   TrUserData);
skip_length_delimited_sc_11011(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_sc_11011(Rest2, 0, 0, F@_1, F@_2,
				F@_3, F@_4, TrUserData).

skip_group_sc_11011(Bin, FNum, Z2, F@_1, F@_2, F@_3,
		    F@_4, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_sc_11011(Rest, 0, Z2, F@_1, F@_2,
				F@_3, F@_4, TrUserData).

skip_32_sc_11011(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, F@_3, F@_4, TrUserData) ->
    dfp_read_field_def_sc_11011(Rest, Z1, Z2, F@_1, F@_2,
				F@_3, F@_4, TrUserData).

skip_64_sc_11011(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, F@_3, F@_4, TrUserData) ->
    dfp_read_field_def_sc_11011(Rest, Z1, Z2, F@_1, F@_2,
				F@_3, F@_4, TrUserData).

d_msg_cs_11012(Bin, TrUserData) ->
    dfp_read_field_def_cs_11012(Bin, 0, 0,
				id(undefined, TrUserData), TrUserData).

dfp_read_field_def_cs_11012(<<8, Rest/binary>>, Z1, Z2,
			    F@_1, TrUserData) ->
    d_field_cs_11012_winPlayerId(Rest, Z1, Z2, F@_1,
				 TrUserData);
dfp_read_field_def_cs_11012(<<>>, 0, 0, F@_1, _) ->
    #cs_11012{winPlayerId = F@_1};
dfp_read_field_def_cs_11012(Other, Z1, Z2, F@_1,
			    TrUserData) ->
    dg_read_field_def_cs_11012(Other, Z1, Z2, F@_1,
			       TrUserData).

dg_read_field_def_cs_11012(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_cs_11012(Rest, N + 7, X bsl N + Acc,
			       F@_1, TrUserData);
dg_read_field_def_cs_11012(<<0:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 ->
	  d_field_cs_11012_winPlayerId(Rest, 0, 0, F@_1,
				       TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_cs_11012(Rest, 0, 0, F@_1, TrUserData);
	    1 -> skip_64_cs_11012(Rest, 0, 0, F@_1, TrUserData);
	    2 ->
		skip_length_delimited_cs_11012(Rest, 0, 0, F@_1,
					       TrUserData);
	    3 ->
		skip_group_cs_11012(Rest, Key bsr 3, 0, F@_1,
				    TrUserData);
	    5 -> skip_32_cs_11012(Rest, 0, 0, F@_1, TrUserData)
	  end
    end;
dg_read_field_def_cs_11012(<<>>, 0, 0, F@_1, _) ->
    #cs_11012{winPlayerId = F@_1}.

d_field_cs_11012_winPlayerId(<<1:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, TrUserData)
    when N < 57 ->
    d_field_cs_11012_winPlayerId(Rest, N + 7, X bsl N + Acc,
				 F@_1, TrUserData);
d_field_cs_11012_winPlayerId(<<0:1, X:7, Rest/binary>>,
			     N, Acc, _, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:64/signed-native>> = <<(X bsl N +
							    Acc):64/unsigned-native>>,
			    Res
			  end,
			  Rest},
    dfp_read_field_def_cs_11012(RestF, 0, 0, NewFValue,
				TrUserData).

skip_varint_cs_11012(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, TrUserData) ->
    skip_varint_cs_11012(Rest, Z1, Z2, F@_1, TrUserData);
skip_varint_cs_11012(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, TrUserData) ->
    dfp_read_field_def_cs_11012(Rest, Z1, Z2, F@_1,
				TrUserData).

skip_length_delimited_cs_11012(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, TrUserData)
    when N < 57 ->
    skip_length_delimited_cs_11012(Rest, N + 7,
				   X bsl N + Acc, F@_1, TrUserData);
skip_length_delimited_cs_11012(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_cs_11012(Rest2, 0, 0, F@_1,
				TrUserData).

skip_group_cs_11012(Bin, FNum, Z2, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_cs_11012(Rest, 0, Z2, F@_1,
				TrUserData).

skip_32_cs_11012(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		 TrUserData) ->
    dfp_read_field_def_cs_11012(Rest, Z1, Z2, F@_1,
				TrUserData).

skip_64_cs_11012(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		 TrUserData) ->
    dfp_read_field_def_cs_11012(Rest, Z1, Z2, F@_1,
				TrUserData).

d_msg_sc_11002(Bin, TrUserData) ->
    dfp_read_field_def_sc_11002(Bin, 0, 0,
				id(undefined, TrUserData),
				id(undefined, TrUserData),
				id(undefined, TrUserData), id([], TrUserData),
				TrUserData).

dfp_read_field_def_sc_11002(<<8, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    d_field_sc_11002_result(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			    F@_4, TrUserData);
dfp_read_field_def_sc_11002(<<16, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    d_field_sc_11002_playerId(Rest, Z1, Z2, F@_1, F@_2,
			      F@_3, F@_4, TrUserData);
dfp_read_field_def_sc_11002(<<26, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    d_field_sc_11002_openId(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			    F@_4, TrUserData);
dfp_read_field_def_sc_11002(<<34, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    d_pfield_sc_11002_seeds(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			    F@_4, TrUserData);
dfp_read_field_def_sc_11002(<<32, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    d_field_sc_11002_seeds(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			   F@_4, TrUserData);
dfp_read_field_def_sc_11002(<<>>, 0, 0, F@_1, F@_2,
			    F@_3, R1, TrUserData) ->
    #sc_11002{result = F@_1, playerId = F@_2, openId = F@_3,
	      seeds = lists_reverse(R1, TrUserData)};
dfp_read_field_def_sc_11002(Other, Z1, Z2, F@_1, F@_2,
			    F@_3, F@_4, TrUserData) ->
    dg_read_field_def_sc_11002(Other, Z1, Z2, F@_1, F@_2,
			       F@_3, F@_4, TrUserData).

dg_read_field_def_sc_11002(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_sc_11002(Rest, N + 7, X bsl N + Acc,
			       F@_1, F@_2, F@_3, F@_4, TrUserData);
dg_read_field_def_sc_11002(<<0:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 ->
	  d_field_sc_11002_result(Rest, 0, 0, F@_1, F@_2, F@_3,
				  F@_4, TrUserData);
      16 ->
	  d_field_sc_11002_playerId(Rest, 0, 0, F@_1, F@_2, F@_3,
				    F@_4, TrUserData);
      26 ->
	  d_field_sc_11002_openId(Rest, 0, 0, F@_1, F@_2, F@_3,
				  F@_4, TrUserData);
      34 ->
	  d_pfield_sc_11002_seeds(Rest, 0, 0, F@_1, F@_2, F@_3,
				  F@_4, TrUserData);
      32 ->
	  d_field_sc_11002_seeds(Rest, 0, 0, F@_1, F@_2, F@_3,
				 F@_4, TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_sc_11002(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4,
				     TrUserData);
	    1 ->
		skip_64_sc_11002(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4,
				 TrUserData);
	    2 ->
		skip_length_delimited_sc_11002(Rest, 0, 0, F@_1, F@_2,
					       F@_3, F@_4, TrUserData);
	    3 ->
		skip_group_sc_11002(Rest, Key bsr 3, 0, F@_1, F@_2,
				    F@_3, F@_4, TrUserData);
	    5 ->
		skip_32_sc_11002(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4,
				 TrUserData)
	  end
    end;
dg_read_field_def_sc_11002(<<>>, 0, 0, F@_1, F@_2, F@_3,
			   R1, TrUserData) ->
    #sc_11002{result = F@_1, playerId = F@_2, openId = F@_3,
	      seeds = lists_reverse(R1, TrUserData)}.

d_field_sc_11002_result(<<1:1, X:7, Rest/binary>>, N,
			Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 57 ->
    d_field_sc_11002_result(Rest, N + 7, X bsl N + Acc,
			    F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_sc_11002_result(<<0:1, X:7, Rest/binary>>, N,
			Acc, _, F@_2, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    Res
			  end,
			  Rest},
    dfp_read_field_def_sc_11002(RestF, 0, 0, NewFValue,
				F@_2, F@_3, F@_4, TrUserData).

d_field_sc_11002_playerId(<<1:1, X:7, Rest/binary>>, N,
			  Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 57 ->
    d_field_sc_11002_playerId(Rest, N + 7, X bsl N + Acc,
			      F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_sc_11002_playerId(<<0:1, X:7, Rest/binary>>, N,
			  Acc, F@_1, _, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:64/signed-native>> = <<(X bsl N +
							    Acc):64/unsigned-native>>,
			    Res
			  end,
			  Rest},
    dfp_read_field_def_sc_11002(RestF, 0, 0, F@_1,
				NewFValue, F@_3, F@_4, TrUserData).

d_field_sc_11002_openId(<<1:1, X:7, Rest/binary>>, N,
			Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 57 ->
    d_field_sc_11002_openId(Rest, N + 7, X bsl N + Acc,
			    F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_sc_11002_openId(<<0:1, X:7, Rest/binary>>, N,
			Acc, F@_1, F@_2, _, F@_4, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Utf8:Len/binary, Rest2/binary>> = Rest,
			   {unicode:characters_to_list(Utf8, unicode), Rest2}
			 end,
    dfp_read_field_def_sc_11002(RestF, 0, 0, F@_1, F@_2,
				NewFValue, F@_4, TrUserData).

d_field_sc_11002_seeds(<<1:1, X:7, Rest/binary>>, N,
		       Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 57 ->
    d_field_sc_11002_seeds(Rest, N + 7, X bsl N + Acc, F@_1,
			   F@_2, F@_3, F@_4, TrUserData);
d_field_sc_11002_seeds(<<0:1, X:7, Rest/binary>>, N,
		       Acc, F@_1, F@_2, F@_3, Prev, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    Res
			  end,
			  Rest},
    dfp_read_field_def_sc_11002(RestF, 0, 0, F@_1, F@_2,
				F@_3, cons(NewFValue, Prev, TrUserData),
				TrUserData).

d_pfield_sc_11002_seeds(<<1:1, X:7, Rest/binary>>, N,
			Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 57 ->
    d_pfield_sc_11002_seeds(Rest, N + 7, X bsl N + Acc,
			    F@_1, F@_2, F@_3, F@_4, TrUserData);
d_pfield_sc_11002_seeds(<<0:1, X:7, Rest/binary>>, N,
			Acc, F@_1, F@_2, F@_3, E, TrUserData) ->
    Len = X bsl N + Acc,
    <<PackedBytes:Len/binary, Rest2/binary>> = Rest,
    NewSeq = d_packed_field_sc_11002_seeds(PackedBytes, 0,
					   0, E),
    dfp_read_field_def_sc_11002(Rest2, 0, 0, F@_1, F@_2,
				F@_3, NewSeq, TrUserData).

d_packed_field_sc_11002_seeds(<<1:1, X:7, Rest/binary>>,
			      N, Acc, AccSeq)
    when N < 57 ->
    d_packed_field_sc_11002_seeds(Rest, N + 7,
				  X bsl N + Acc, AccSeq);
d_packed_field_sc_11002_seeds(<<0:1, X:7, Rest/binary>>,
			      N, Acc, AccSeq) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    Res
			  end,
			  Rest},
    d_packed_field_sc_11002_seeds(RestF, 0, 0,
				  [NewFValue | AccSeq]);
d_packed_field_sc_11002_seeds(<<>>, 0, 0, AccSeq) ->
    AccSeq.

skip_varint_sc_11002(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    skip_varint_sc_11002(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			 F@_4, TrUserData);
skip_varint_sc_11002(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    dfp_read_field_def_sc_11002(Rest, Z1, Z2, F@_1, F@_2,
				F@_3, F@_4, TrUserData).

skip_length_delimited_sc_11002(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 57 ->
    skip_length_delimited_sc_11002(Rest, N + 7,
				   X bsl N + Acc, F@_1, F@_2, F@_3, F@_4,
				   TrUserData);
skip_length_delimited_sc_11002(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_sc_11002(Rest2, 0, 0, F@_1, F@_2,
				F@_3, F@_4, TrUserData).

skip_group_sc_11002(Bin, FNum, Z2, F@_1, F@_2, F@_3,
		    F@_4, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_sc_11002(Rest, 0, Z2, F@_1, F@_2,
				F@_3, F@_4, TrUserData).

skip_32_sc_11002(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, F@_3, F@_4, TrUserData) ->
    dfp_read_field_def_sc_11002(Rest, Z1, Z2, F@_1, F@_2,
				F@_3, F@_4, TrUserData).

skip_64_sc_11002(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, F@_3, F@_4, TrUserData) ->
    dfp_read_field_def_sc_11002(Rest, Z1, Z2, F@_1, F@_2,
				F@_3, F@_4, TrUserData).

d_msg_sc_11010(Bin, TrUserData) ->
    dfp_read_field_def_sc_11010(Bin, 0, 0,
				id(undefined, TrUserData),
				id(undefined, TrUserData), TrUserData).

dfp_read_field_def_sc_11010(<<8, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, TrUserData) ->
    d_field_sc_11010_playerId(Rest, Z1, Z2, F@_1, F@_2,
			      TrUserData);
dfp_read_field_def_sc_11010(<<18, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, TrUserData) ->
    d_field_sc_11010_processData(Rest, Z1, Z2, F@_1, F@_2,
				 TrUserData);
dfp_read_field_def_sc_11010(<<>>, 0, 0, F@_1, F@_2,
			    _) ->
    #sc_11010{playerId = F@_1, processData = F@_2};
dfp_read_field_def_sc_11010(Other, Z1, Z2, F@_1, F@_2,
			    TrUserData) ->
    dg_read_field_def_sc_11010(Other, Z1, Z2, F@_1, F@_2,
			       TrUserData).

dg_read_field_def_sc_11010(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_sc_11010(Rest, N + 7, X bsl N + Acc,
			       F@_1, F@_2, TrUserData);
dg_read_field_def_sc_11010(<<0:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 ->
	  d_field_sc_11010_playerId(Rest, 0, 0, F@_1, F@_2,
				    TrUserData);
      18 ->
	  d_field_sc_11010_processData(Rest, 0, 0, F@_1, F@_2,
				       TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_sc_11010(Rest, 0, 0, F@_1, F@_2,
				     TrUserData);
	    1 ->
		skip_64_sc_11010(Rest, 0, 0, F@_1, F@_2, TrUserData);
	    2 ->
		skip_length_delimited_sc_11010(Rest, 0, 0, F@_1, F@_2,
					       TrUserData);
	    3 ->
		skip_group_sc_11010(Rest, Key bsr 3, 0, F@_1, F@_2,
				    TrUserData);
	    5 ->
		skip_32_sc_11010(Rest, 0, 0, F@_1, F@_2, TrUserData)
	  end
    end;
dg_read_field_def_sc_11010(<<>>, 0, 0, F@_1, F@_2, _) ->
    #sc_11010{playerId = F@_1, processData = F@_2}.

d_field_sc_11010_playerId(<<1:1, X:7, Rest/binary>>, N,
			  Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_sc_11010_playerId(Rest, N + 7, X bsl N + Acc,
			      F@_1, F@_2, TrUserData);
d_field_sc_11010_playerId(<<0:1, X:7, Rest/binary>>, N,
			  Acc, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:64/signed-native>> = <<(X bsl N +
							    Acc):64/unsigned-native>>,
			    Res
			  end,
			  Rest},
    dfp_read_field_def_sc_11010(RestF, 0, 0, NewFValue,
				F@_2, TrUserData).

d_field_sc_11010_processData(<<1:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_sc_11010_processData(Rest, N + 7, X bsl N + Acc,
				 F@_1, F@_2, TrUserData);
d_field_sc_11010_processData(<<0:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Bytes:Len/binary, Rest2/binary>> = Rest,
			   {binary:copy(Bytes), Rest2}
			 end,
    dfp_read_field_def_sc_11010(RestF, 0, 0, F@_1,
				NewFValue, TrUserData).

skip_varint_sc_11010(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, TrUserData) ->
    skip_varint_sc_11010(Rest, Z1, Z2, F@_1, F@_2,
			 TrUserData);
skip_varint_sc_11010(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, TrUserData) ->
    dfp_read_field_def_sc_11010(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

skip_length_delimited_sc_11010(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    skip_length_delimited_sc_11010(Rest, N + 7,
				   X bsl N + Acc, F@_1, F@_2, TrUserData);
skip_length_delimited_sc_11010(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_sc_11010(Rest2, 0, 0, F@_1, F@_2,
				TrUserData).

skip_group_sc_11010(Bin, FNum, Z2, F@_1, F@_2,
		    TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_sc_11010(Rest, 0, Z2, F@_1, F@_2,
				TrUserData).

skip_32_sc_11010(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, TrUserData) ->
    dfp_read_field_def_sc_11010(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

skip_64_sc_11010(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, TrUserData) ->
    dfp_read_field_def_sc_11010(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData).

d_msg_cs_11013(Bin, TrUserData) ->
    dfp_read_field_def_cs_11013(Bin, 0, 0, TrUserData).

dfp_read_field_def_cs_11013(<<>>, 0, 0, _) ->
    #cs_11013{};
dfp_read_field_def_cs_11013(Other, Z1, Z2,
			    TrUserData) ->
    dg_read_field_def_cs_11013(Other, Z1, Z2, TrUserData).

dg_read_field_def_cs_11013(<<1:1, X:7, Rest/binary>>, N,
			   Acc, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_cs_11013(Rest, N + 7, X bsl N + Acc,
			       TrUserData);
dg_read_field_def_cs_11013(<<0:1, X:7, Rest/binary>>, N,
			   Acc, TrUserData) ->
    Key = X bsl N + Acc,
    case Key band 7 of
      0 -> skip_varint_cs_11013(Rest, 0, 0, TrUserData);
      1 -> skip_64_cs_11013(Rest, 0, 0, TrUserData);
      2 ->
	  skip_length_delimited_cs_11013(Rest, 0, 0, TrUserData);
      3 ->
	  skip_group_cs_11013(Rest, Key bsr 3, 0, TrUserData);
      5 -> skip_32_cs_11013(Rest, 0, 0, TrUserData)
    end;
dg_read_field_def_cs_11013(<<>>, 0, 0, _) ->
    #cs_11013{}.

skip_varint_cs_11013(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		     TrUserData) ->
    skip_varint_cs_11013(Rest, Z1, Z2, TrUserData);
skip_varint_cs_11013(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		     TrUserData) ->
    dfp_read_field_def_cs_11013(Rest, Z1, Z2, TrUserData).

skip_length_delimited_cs_11013(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, TrUserData)
    when N < 57 ->
    skip_length_delimited_cs_11013(Rest, N + 7,
				   X bsl N + Acc, TrUserData);
skip_length_delimited_cs_11013(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_cs_11013(Rest2, 0, 0, TrUserData).

skip_group_cs_11013(Bin, FNum, Z2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_cs_11013(Rest, 0, Z2, TrUserData).

skip_32_cs_11013(<<_:32, Rest/binary>>, Z1, Z2,
		 TrUserData) ->
    dfp_read_field_def_cs_11013(Rest, Z1, Z2, TrUserData).

skip_64_cs_11013(<<_:64, Rest/binary>>, Z1, Z2,
		 TrUserData) ->
    dfp_read_field_def_cs_11013(Rest, Z1, Z2, TrUserData).

d_msg_cs_11004(Bin, TrUserData) ->
    dfp_read_field_def_cs_11004(Bin, 0, 0, TrUserData).

dfp_read_field_def_cs_11004(<<>>, 0, 0, _) ->
    #cs_11004{};
dfp_read_field_def_cs_11004(Other, Z1, Z2,
			    TrUserData) ->
    dg_read_field_def_cs_11004(Other, Z1, Z2, TrUserData).

dg_read_field_def_cs_11004(<<1:1, X:7, Rest/binary>>, N,
			   Acc, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_cs_11004(Rest, N + 7, X bsl N + Acc,
			       TrUserData);
dg_read_field_def_cs_11004(<<0:1, X:7, Rest/binary>>, N,
			   Acc, TrUserData) ->
    Key = X bsl N + Acc,
    case Key band 7 of
      0 -> skip_varint_cs_11004(Rest, 0, 0, TrUserData);
      1 -> skip_64_cs_11004(Rest, 0, 0, TrUserData);
      2 ->
	  skip_length_delimited_cs_11004(Rest, 0, 0, TrUserData);
      3 ->
	  skip_group_cs_11004(Rest, Key bsr 3, 0, TrUserData);
      5 -> skip_32_cs_11004(Rest, 0, 0, TrUserData)
    end;
dg_read_field_def_cs_11004(<<>>, 0, 0, _) ->
    #cs_11004{}.

skip_varint_cs_11004(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		     TrUserData) ->
    skip_varint_cs_11004(Rest, Z1, Z2, TrUserData);
skip_varint_cs_11004(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		     TrUserData) ->
    dfp_read_field_def_cs_11004(Rest, Z1, Z2, TrUserData).

skip_length_delimited_cs_11004(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, TrUserData)
    when N < 57 ->
    skip_length_delimited_cs_11004(Rest, N + 7,
				   X bsl N + Acc, TrUserData);
skip_length_delimited_cs_11004(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_cs_11004(Rest2, 0, 0, TrUserData).

skip_group_cs_11004(Bin, FNum, Z2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_cs_11004(Rest, 0, Z2, TrUserData).

skip_32_cs_11004(<<_:32, Rest/binary>>, Z1, Z2,
		 TrUserData) ->
    dfp_read_field_def_cs_11004(Rest, Z1, Z2, TrUserData).

skip_64_cs_11004(<<_:64, Rest/binary>>, Z1, Z2,
		 TrUserData) ->
    dfp_read_field_def_cs_11004(Rest, Z1, Z2, TrUserData).

d_msg_cs_11002(Bin, TrUserData) ->
    dfp_read_field_def_cs_11002(Bin, 0, 0, TrUserData).

dfp_read_field_def_cs_11002(<<>>, 0, 0, _) ->
    #cs_11002{};
dfp_read_field_def_cs_11002(Other, Z1, Z2,
			    TrUserData) ->
    dg_read_field_def_cs_11002(Other, Z1, Z2, TrUserData).

dg_read_field_def_cs_11002(<<1:1, X:7, Rest/binary>>, N,
			   Acc, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_cs_11002(Rest, N + 7, X bsl N + Acc,
			       TrUserData);
dg_read_field_def_cs_11002(<<0:1, X:7, Rest/binary>>, N,
			   Acc, TrUserData) ->
    Key = X bsl N + Acc,
    case Key band 7 of
      0 -> skip_varint_cs_11002(Rest, 0, 0, TrUserData);
      1 -> skip_64_cs_11002(Rest, 0, 0, TrUserData);
      2 ->
	  skip_length_delimited_cs_11002(Rest, 0, 0, TrUserData);
      3 ->
	  skip_group_cs_11002(Rest, Key bsr 3, 0, TrUserData);
      5 -> skip_32_cs_11002(Rest, 0, 0, TrUserData)
    end;
dg_read_field_def_cs_11002(<<>>, 0, 0, _) ->
    #cs_11002{}.

skip_varint_cs_11002(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		     TrUserData) ->
    skip_varint_cs_11002(Rest, Z1, Z2, TrUserData);
skip_varint_cs_11002(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		     TrUserData) ->
    dfp_read_field_def_cs_11002(Rest, Z1, Z2, TrUserData).

skip_length_delimited_cs_11002(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, TrUserData)
    when N < 57 ->
    skip_length_delimited_cs_11002(Rest, N + 7,
				   X bsl N + Acc, TrUserData);
skip_length_delimited_cs_11002(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_cs_11002(Rest2, 0, 0, TrUserData).

skip_group_cs_11002(Bin, FNum, Z2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_cs_11002(Rest, 0, Z2, TrUserData).

skip_32_cs_11002(<<_:32, Rest/binary>>, Z1, Z2,
		 TrUserData) ->
    dfp_read_field_def_cs_11002(Rest, Z1, Z2, TrUserData).

skip_64_cs_11002(<<_:64, Rest/binary>>, Z1, Z2,
		 TrUserData) ->
    dfp_read_field_def_cs_11002(Rest, Z1, Z2, TrUserData).

d_msg_cs_11011(Bin, TrUserData) ->
    dfp_read_field_def_cs_11011(Bin, 0, 0,
				id(undefined, TrUserData),
				id(undefined, TrUserData),
				id(undefined, TrUserData),
				id(undefined, TrUserData), TrUserData).

dfp_read_field_def_cs_11011(<<8, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    d_field_cs_11011_playerScore(Rest, Z1, Z2, F@_1, F@_2,
				 F@_3, F@_4, TrUserData);
dfp_read_field_def_cs_11011(<<18, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    d_field_cs_11011_resultData(Rest, Z1, Z2, F@_1, F@_2,
				F@_3, F@_4, TrUserData);
dfp_read_field_def_cs_11011(<<24, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    d_field_cs_11011_level(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			   F@_4, TrUserData);
dfp_read_field_def_cs_11011(<<32, Rest/binary>>, Z1, Z2,
			    F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    d_field_cs_11011_score2(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			    F@_4, TrUserData);
dfp_read_field_def_cs_11011(<<>>, 0, 0, F@_1, F@_2,
			    F@_3, F@_4, _) ->
    #cs_11011{playerScore = F@_1, resultData = F@_2,
	      level = F@_3, score2 = F@_4};
dfp_read_field_def_cs_11011(Other, Z1, Z2, F@_1, F@_2,
			    F@_3, F@_4, TrUserData) ->
    dg_read_field_def_cs_11011(Other, Z1, Z2, F@_1, F@_2,
			       F@_3, F@_4, TrUserData).

dg_read_field_def_cs_11011(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_cs_11011(Rest, N + 7, X bsl N + Acc,
			       F@_1, F@_2, F@_3, F@_4, TrUserData);
dg_read_field_def_cs_11011(<<0:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 ->
	  d_field_cs_11011_playerScore(Rest, 0, 0, F@_1, F@_2,
				       F@_3, F@_4, TrUserData);
      18 ->
	  d_field_cs_11011_resultData(Rest, 0, 0, F@_1, F@_2,
				      F@_3, F@_4, TrUserData);
      24 ->
	  d_field_cs_11011_level(Rest, 0, 0, F@_1, F@_2, F@_3,
				 F@_4, TrUserData);
      32 ->
	  d_field_cs_11011_score2(Rest, 0, 0, F@_1, F@_2, F@_3,
				  F@_4, TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_cs_11011(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4,
				     TrUserData);
	    1 ->
		skip_64_cs_11011(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4,
				 TrUserData);
	    2 ->
		skip_length_delimited_cs_11011(Rest, 0, 0, F@_1, F@_2,
					       F@_3, F@_4, TrUserData);
	    3 ->
		skip_group_cs_11011(Rest, Key bsr 3, 0, F@_1, F@_2,
				    F@_3, F@_4, TrUserData);
	    5 ->
		skip_32_cs_11011(Rest, 0, 0, F@_1, F@_2, F@_3, F@_4,
				 TrUserData)
	  end
    end;
dg_read_field_def_cs_11011(<<>>, 0, 0, F@_1, F@_2, F@_3,
			   F@_4, _) ->
    #cs_11011{playerScore = F@_1, resultData = F@_2,
	      level = F@_3, score2 = F@_4}.

d_field_cs_11011_playerScore(<<1:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 57 ->
    d_field_cs_11011_playerScore(Rest, N + 7, X bsl N + Acc,
				 F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_cs_11011_playerScore(<<0:1, X:7, Rest/binary>>,
			     N, Acc, _, F@_2, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    Res
			  end,
			  Rest},
    dfp_read_field_def_cs_11011(RestF, 0, 0, NewFValue,
				F@_2, F@_3, F@_4, TrUserData).

d_field_cs_11011_resultData(<<1:1, X:7, Rest/binary>>,
			    N, Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 57 ->
    d_field_cs_11011_resultData(Rest, N + 7, X bsl N + Acc,
				F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_cs_11011_resultData(<<0:1, X:7, Rest/binary>>,
			    N, Acc, F@_1, _, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Bytes:Len/binary, Rest2/binary>> = Rest,
			   {binary:copy(Bytes), Rest2}
			 end,
    dfp_read_field_def_cs_11011(RestF, 0, 0, F@_1,
				NewFValue, F@_3, F@_4, TrUserData).

d_field_cs_11011_level(<<1:1, X:7, Rest/binary>>, N,
		       Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 57 ->
    d_field_cs_11011_level(Rest, N + 7, X bsl N + Acc, F@_1,
			   F@_2, F@_3, F@_4, TrUserData);
d_field_cs_11011_level(<<0:1, X:7, Rest/binary>>, N,
		       Acc, F@_1, F@_2, _, F@_4, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    Res
			  end,
			  Rest},
    dfp_read_field_def_cs_11011(RestF, 0, 0, F@_1, F@_2,
				NewFValue, F@_4, TrUserData).

d_field_cs_11011_score2(<<1:1, X:7, Rest/binary>>, N,
			Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 57 ->
    d_field_cs_11011_score2(Rest, N + 7, X bsl N + Acc,
			    F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_cs_11011_score2(<<0:1, X:7, Rest/binary>>, N,
			Acc, F@_1, F@_2, F@_3, _, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    Res
			  end,
			  Rest},
    dfp_read_field_def_cs_11011(RestF, 0, 0, F@_1, F@_2,
				F@_3, NewFValue, TrUserData).

skip_varint_cs_11011(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    skip_varint_cs_11011(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			 F@_4, TrUserData);
skip_varint_cs_11011(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    dfp_read_field_def_cs_11011(Rest, Z1, Z2, F@_1, F@_2,
				F@_3, F@_4, TrUserData).

skip_length_delimited_cs_11011(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, F@_3, F@_4, TrUserData)
    when N < 57 ->
    skip_length_delimited_cs_11011(Rest, N + 7,
				   X bsl N + Acc, F@_1, F@_2, F@_3, F@_4,
				   TrUserData);
skip_length_delimited_cs_11011(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_cs_11011(Rest2, 0, 0, F@_1, F@_2,
				F@_3, F@_4, TrUserData).

skip_group_cs_11011(Bin, FNum, Z2, F@_1, F@_2, F@_3,
		    F@_4, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_cs_11011(Rest, 0, Z2, F@_1, F@_2,
				F@_3, F@_4, TrUserData).

skip_32_cs_11011(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, F@_3, F@_4, TrUserData) ->
    dfp_read_field_def_cs_11011(Rest, Z1, Z2, F@_1, F@_2,
				F@_3, F@_4, TrUserData).

skip_64_cs_11011(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		 F@_2, F@_3, F@_4, TrUserData) ->
    dfp_read_field_def_cs_11011(Rest, Z1, Z2, F@_1, F@_2,
				F@_3, F@_4, TrUserData).

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New) -> merge_msgs(Prev, New, []).

merge_msgs(Prev, New, Opts)
    when element(1, Prev) =:= element(1, New) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case Prev of
      #sc_11012{} ->
	  merge_msg_sc_11012(Prev, New, TrUserData);
      #playerInfo{} ->
	  merge_msg_playerInfo(Prev, New, TrUserData);
      #sc_11003{} ->
	  merge_msg_sc_11003(Prev, New, TrUserData);
      #cs_11010{} ->
	  merge_msg_cs_11010(Prev, New, TrUserData);
      #sc_11011{} ->
	  merge_msg_sc_11011(Prev, New, TrUserData);
      #cs_11012{} ->
	  merge_msg_cs_11012(Prev, New, TrUserData);
      #sc_11002{} ->
	  merge_msg_sc_11002(Prev, New, TrUserData);
      #sc_11010{} ->
	  merge_msg_sc_11010(Prev, New, TrUserData);
      #cs_11013{} ->
	  merge_msg_cs_11013(Prev, New, TrUserData);
      #cs_11004{} ->
	  merge_msg_cs_11004(Prev, New, TrUserData);
      #cs_11002{} ->
	  merge_msg_cs_11002(Prev, New, TrUserData);
      #cs_11011{} -> merge_msg_cs_11011(Prev, New, TrUserData)
    end.

merge_msg_sc_11012(#sc_11012{},
		   #sc_11012{result = NFresult,
			     winPlayerId = NFwinPlayerId},
		   _) ->
    #sc_11012{result = NFresult,
	      winPlayerId = NFwinPlayerId}.

merge_msg_playerInfo(#playerInfo{battleTimes =
				     PFbattleTimes,
				 robotLevel = PFrobotLevel},
		     #playerInfo{playerId = NFplayerId, openId = NFopenId,
				 nickname = NFnickname, avatarUrl = NFavatarUrl,
				 isRobot = NFisRobot, gender = NFgender,
				 battleTimes = NFbattleTimes,
				 robotLevel = NFrobotLevel},
		     _) ->
    #playerInfo{playerId = NFplayerId, openId = NFopenId,
		nickname = NFnickname, avatarUrl = NFavatarUrl,
		isRobot = NFisRobot, gender = NFgender,
		battleTimes =
		    if NFbattleTimes =:= undefined -> PFbattleTimes;
		       true -> NFbattleTimes
		    end,
		robotLevel =
		    if NFrobotLevel =:= undefined -> PFrobotLevel;
		       true -> NFrobotLevel
		    end}.

merge_msg_sc_11003(#sc_11003{playerInfos =
				 PFplayerInfos},
		   #sc_11003{readyTime = NFreadyTime,
			     playerInfos = NFplayerInfos},
		   TrUserData) ->
    #sc_11003{readyTime = NFreadyTime,
	      playerInfos =
		  if PFplayerInfos /= undefined,
		     NFplayerInfos /= undefined ->
			 'erlang_++'(PFplayerInfos, NFplayerInfos, TrUserData);
		     PFplayerInfos == undefined -> NFplayerInfos;
		     NFplayerInfos == undefined -> PFplayerInfos
		  end}.

merge_msg_cs_11010(#cs_11010{},
		   #cs_11010{processData = NFprocessData}, _) ->
    #cs_11010{processData = NFprocessData}.

merge_msg_sc_11011(#sc_11011{seeds = PFseeds},
		   #sc_11011{playerId = NFplayerId,
			     playerScore = NFplayerScore,
			     resultData = NFresultData, seeds = NFseeds},
		   TrUserData) ->
    #sc_11011{playerId = NFplayerId,
	      playerScore = NFplayerScore, resultData = NFresultData,
	      seeds =
		  if PFseeds /= undefined, NFseeds /= undefined ->
			 'erlang_++'(PFseeds, NFseeds, TrUserData);
		     PFseeds == undefined -> NFseeds;
		     NFseeds == undefined -> PFseeds
		  end}.

merge_msg_cs_11012(#cs_11012{},
		   #cs_11012{winPlayerId = NFwinPlayerId}, _) ->
    #cs_11012{winPlayerId = NFwinPlayerId}.

merge_msg_sc_11002(#sc_11002{seeds = PFseeds},
		   #sc_11002{result = NFresult, playerId = NFplayerId,
			     openId = NFopenId, seeds = NFseeds},
		   TrUserData) ->
    #sc_11002{result = NFresult, playerId = NFplayerId,
	      openId = NFopenId,
	      seeds =
		  if PFseeds /= undefined, NFseeds /= undefined ->
			 'erlang_++'(PFseeds, NFseeds, TrUserData);
		     PFseeds == undefined -> NFseeds;
		     NFseeds == undefined -> PFseeds
		  end}.

merge_msg_sc_11010(#sc_11010{},
		   #sc_11010{playerId = NFplayerId,
			     processData = NFprocessData},
		   _) ->
    #sc_11010{playerId = NFplayerId,
	      processData = NFprocessData}.

merge_msg_cs_11013(_Prev, New, _TrUserData) -> New.

merge_msg_cs_11004(_Prev, New, _TrUserData) -> New.

merge_msg_cs_11002(_Prev, New, _TrUserData) -> New.

merge_msg_cs_11011(#cs_11011{level = PFlevel,
			     score2 = PFscore2},
		   #cs_11011{playerScore = NFplayerScore,
			     resultData = NFresultData, level = NFlevel,
			     score2 = NFscore2},
		   _) ->
    #cs_11011{playerScore = NFplayerScore,
	      resultData = NFresultData,
	      level =
		  if NFlevel =:= undefined -> PFlevel;
		     true -> NFlevel
		  end,
	      score2 =
		  if NFscore2 =:= undefined -> PFscore2;
		     true -> NFscore2
		  end}.


verify_msg(Msg) -> verify_msg(Msg, []).

verify_msg(Msg, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case Msg of
      #sc_11012{} ->
	  v_msg_sc_11012(Msg, [sc_11012], TrUserData);
      #playerInfo{} ->
	  v_msg_playerInfo(Msg, [playerInfo], TrUserData);
      #sc_11003{} ->
	  v_msg_sc_11003(Msg, [sc_11003], TrUserData);
      #cs_11010{} ->
	  v_msg_cs_11010(Msg, [cs_11010], TrUserData);
      #sc_11011{} ->
	  v_msg_sc_11011(Msg, [sc_11011], TrUserData);
      #cs_11012{} ->
	  v_msg_cs_11012(Msg, [cs_11012], TrUserData);
      #sc_11002{} ->
	  v_msg_sc_11002(Msg, [sc_11002], TrUserData);
      #sc_11010{} ->
	  v_msg_sc_11010(Msg, [sc_11010], TrUserData);
      #cs_11013{} ->
	  v_msg_cs_11013(Msg, [cs_11013], TrUserData);
      #cs_11004{} ->
	  v_msg_cs_11004(Msg, [cs_11004], TrUserData);
      #cs_11002{} ->
	  v_msg_cs_11002(Msg, [cs_11002], TrUserData);
      #cs_11011{} ->
	  v_msg_cs_11011(Msg, [cs_11011], TrUserData);
      _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-dialyzer({nowarn_function,v_msg_sc_11012/3}).
v_msg_sc_11012(#sc_11012{result = F1, winPlayerId = F2},
	       Path, _) ->
    v_type_int32(F1, [result | Path]),
    v_type_int64(F2, [winPlayerId | Path]),
    ok.

-dialyzer({nowarn_function,v_msg_playerInfo/3}).
v_msg_playerInfo(#playerInfo{playerId = F1, openId = F2,
			     nickname = F3, avatarUrl = F4, isRobot = F5,
			     gender = F6, battleTimes = F7, robotLevel = F8},
		 Path, _) ->
    v_type_int64(F1, [playerId | Path]),
    v_type_string(F2, [openId | Path]),
    v_type_string(F3, [nickname | Path]),
    v_type_string(F4, [avatarUrl | Path]),
    v_type_int32(F5, [isRobot | Path]),
    v_type_int32(F6, [gender | Path]),
    if F7 == undefined -> ok;
       true -> v_type_int32(F7, [battleTimes | Path])
    end,
    if F8 == undefined -> ok;
       true -> v_type_int32(F8, [robotLevel | Path])
    end,
    ok;
v_msg_playerInfo(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, playerInfo}, X, Path).

-dialyzer({nowarn_function,v_msg_sc_11003/3}).
v_msg_sc_11003(#sc_11003{readyTime = F1,
			 playerInfos = F2},
	       Path, TrUserData) ->
    v_type_int32(F1, [readyTime | Path]),
    if is_list(F2) ->
	   _ = [v_msg_playerInfo(Elem, [playerInfos | Path],
				 TrUserData)
		|| Elem <- F2],
	   ok;
       true ->
	   mk_type_error({invalid_list_of, {msg, playerInfo}}, F2,
			 [playerInfos | Path])
    end,
    ok.

-dialyzer({nowarn_function,v_msg_cs_11010/3}).
v_msg_cs_11010(#cs_11010{processData = F1}, Path, _) ->
    v_type_bytes(F1, [processData | Path]), ok.

-dialyzer({nowarn_function,v_msg_sc_11011/3}).
v_msg_sc_11011(#sc_11011{playerId = F1,
			 playerScore = F2, resultData = F3, seeds = F4},
	       Path, _) ->
    v_type_int64(F1, [playerId | Path]),
    v_type_int32(F2, [playerScore | Path]),
    v_type_bytes(F3, [resultData | Path]),
    if is_list(F4) ->
	   _ = [v_type_int32(Elem, [seeds | Path]) || Elem <- F4],
	   ok;
       true ->
	   mk_type_error({invalid_list_of, int32}, F4,
			 [seeds | Path])
    end,
    ok.

-dialyzer({nowarn_function,v_msg_cs_11012/3}).
v_msg_cs_11012(#cs_11012{winPlayerId = F1}, Path, _) ->
    v_type_int64(F1, [winPlayerId | Path]), ok.

-dialyzer({nowarn_function,v_msg_sc_11002/3}).
v_msg_sc_11002(#sc_11002{result = F1, playerId = F2,
			 openId = F3, seeds = F4},
	       Path, _) ->
    v_type_int32(F1, [result | Path]),
    v_type_int64(F2, [playerId | Path]),
    v_type_string(F3, [openId | Path]),
    if is_list(F4) ->
	   _ = [v_type_int32(Elem, [seeds | Path]) || Elem <- F4],
	   ok;
       true ->
	   mk_type_error({invalid_list_of, int32}, F4,
			 [seeds | Path])
    end,
    ok.

-dialyzer({nowarn_function,v_msg_sc_11010/3}).
v_msg_sc_11010(#sc_11010{playerId = F1,
			 processData = F2},
	       Path, _) ->
    v_type_int64(F1, [playerId | Path]),
    v_type_bytes(F2, [processData | Path]),
    ok.

-dialyzer({nowarn_function,v_msg_cs_11013/3}).
v_msg_cs_11013(#cs_11013{}, _Path, _) -> ok.

-dialyzer({nowarn_function,v_msg_cs_11004/3}).
v_msg_cs_11004(#cs_11004{}, _Path, _) -> ok.

-dialyzer({nowarn_function,v_msg_cs_11002/3}).
v_msg_cs_11002(#cs_11002{}, _Path, _) -> ok.

-dialyzer({nowarn_function,v_msg_cs_11011/3}).
v_msg_cs_11011(#cs_11011{playerScore = F1,
			 resultData = F2, level = F3, score2 = F4},
	       Path, _) ->
    v_type_int32(F1, [playerScore | Path]),
    v_type_bytes(F2, [resultData | Path]),
    if F3 == undefined -> ok;
       true -> v_type_int32(F3, [level | Path])
    end,
    if F4 == undefined -> ok;
       true -> v_type_int32(F4, [score2 | Path])
    end,
    ok.

-dialyzer({nowarn_function,v_type_int32/2}).
v_type_int32(N, _Path)
    when -2147483648 =< N, N =< 2147483647 ->
    ok;
v_type_int32(N, Path) when is_integer(N) ->
    mk_type_error({value_out_of_range, int32, signed, 32},
		  N, Path);
v_type_int32(X, Path) ->
    mk_type_error({bad_integer, int32, signed, 32}, X,
		  Path).

-dialyzer({nowarn_function,v_type_int64/2}).
v_type_int64(N, _Path)
    when -9223372036854775808 =< N,
	 N =< 9223372036854775807 ->
    ok;
v_type_int64(N, Path) when is_integer(N) ->
    mk_type_error({value_out_of_range, int64, signed, 64},
		  N, Path);
v_type_int64(X, Path) ->
    mk_type_error({bad_integer, int64, signed, 64}, X,
		  Path).

-dialyzer({nowarn_function,v_type_string/2}).
v_type_string(S, Path) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
      B when is_binary(B) -> ok;
      {error, _, _} ->
	  mk_type_error(bad_unicode_string, S, Path)
    catch
      error:badarg ->
	  mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path) ->
    mk_type_error(bad_unicode_string, X, Path).

-dialyzer({nowarn_function,v_type_bytes/2}).
v_type_bytes(B, _Path) when is_binary(B) -> ok;
v_type_bytes(B, _Path) when is_list(B) -> ok;
v_type_bytes(X, Path) ->
    mk_type_error(bad_binary_value, X, Path).

-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error,
		  {Error, [{value, ValueSeen}, {path, Path2}]}}).


-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) ->
    list_to_atom(lists:append(lists:join(".",
					 lists:map(fun atom_to_list/1,
						   lists:reverse(PathR))))).


-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.

get_msg_defs() ->
    [{{msg, sc_11012},
      [#field{name = result, fnum = 1, rnum = 2, type = int32,
	      occurrence = required, opts = []},
       #field{name = winPlayerId, fnum = 2, rnum = 3,
	      type = int64, occurrence = required, opts = []}]},
     {{msg, playerInfo},
      [#field{name = playerId, fnum = 1, rnum = 2,
	      type = int64, occurrence = required, opts = []},
       #field{name = openId, fnum = 2, rnum = 3, type = string,
	      occurrence = required, opts = []},
       #field{name = nickname, fnum = 3, rnum = 4,
	      type = string, occurrence = required, opts = []},
       #field{name = avatarUrl, fnum = 4, rnum = 5,
	      type = string, occurrence = required, opts = []},
       #field{name = isRobot, fnum = 5, rnum = 6, type = int32,
	      occurrence = required, opts = []},
       #field{name = gender, fnum = 6, rnum = 7, type = int32,
	      occurrence = required, opts = []},
       #field{name = battleTimes, fnum = 7, rnum = 8,
	      type = int32, occurrence = optional, opts = []},
       #field{name = robotLevel, fnum = 8, rnum = 9,
	      type = int32, occurrence = optional, opts = []}]},
     {{msg, sc_11003},
      [#field{name = readyTime, fnum = 1, rnum = 2,
	      type = int32, occurrence = required, opts = []},
       #field{name = playerInfos, fnum = 2, rnum = 3,
	      type = {msg, playerInfo}, occurrence = repeated,
	      opts = []}]},
     {{msg, cs_11010},
      [#field{name = processData, fnum = 1, rnum = 2,
	      type = bytes, occurrence = required, opts = []}]},
     {{msg, sc_11011},
      [#field{name = playerId, fnum = 1, rnum = 2,
	      type = int64, occurrence = required, opts = []},
       #field{name = playerScore, fnum = 2, rnum = 3,
	      type = int32, occurrence = required, opts = []},
       #field{name = resultData, fnum = 3, rnum = 4,
	      type = bytes, occurrence = required, opts = []},
       #field{name = seeds, fnum = 4, rnum = 5, type = int32,
	      occurrence = repeated, opts = []}]},
     {{msg, cs_11012},
      [#field{name = winPlayerId, fnum = 1, rnum = 2,
	      type = int64, occurrence = required, opts = []}]},
     {{msg, sc_11002},
      [#field{name = result, fnum = 1, rnum = 2, type = int32,
	      occurrence = required, opts = []},
       #field{name = playerId, fnum = 2, rnum = 3,
	      type = int64, occurrence = required, opts = []},
       #field{name = openId, fnum = 3, rnum = 4, type = string,
	      occurrence = required, opts = []},
       #field{name = seeds, fnum = 4, rnum = 5, type = int32,
	      occurrence = repeated, opts = []}]},
     {{msg, sc_11010},
      [#field{name = playerId, fnum = 1, rnum = 2,
	      type = int64, occurrence = required, opts = []},
       #field{name = processData, fnum = 2, rnum = 3,
	      type = bytes, occurrence = required, opts = []}]},
     {{msg, cs_11013}, []}, {{msg, cs_11004}, []},
     {{msg, cs_11002}, []},
     {{msg, cs_11011},
      [#field{name = playerScore, fnum = 1, rnum = 2,
	      type = int32, occurrence = required, opts = []},
       #field{name = resultData, fnum = 2, rnum = 3,
	      type = bytes, occurrence = required, opts = []},
       #field{name = level, fnum = 3, rnum = 4, type = int32,
	      occurrence = optional, opts = []},
       #field{name = score2, fnum = 4, rnum = 5, type = int32,
	      occurrence = optional, opts = []}]}].


get_msg_names() ->
    [sc_11012, playerInfo, sc_11003, cs_11010, sc_11011,
     cs_11012, sc_11002, sc_11010, cs_11013, cs_11004,
     cs_11002, cs_11011].


get_group_names() -> [].


get_msg_or_group_names() ->
    [sc_11012, playerInfo, sc_11003, cs_11010, sc_11011,
     cs_11012, sc_11002, sc_11010, cs_11013, cs_11004,
     cs_11002, cs_11011].


get_enum_names() -> [].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
      Fs when is_list(Fs) -> Fs;
      error -> erlang:error({no_such_msg, MsgName})
    end.


-spec fetch_enum_def(_) -> no_return().
fetch_enum_def(EnumName) ->
    erlang:error({no_such_enum, EnumName}).


find_msg_def(sc_11012) ->
    [#field{name = result, fnum = 1, rnum = 2, type = int32,
	    occurrence = required, opts = []},
     #field{name = winPlayerId, fnum = 2, rnum = 3,
	    type = int64, occurrence = required, opts = []}];
find_msg_def(playerInfo) ->
    [#field{name = playerId, fnum = 1, rnum = 2,
	    type = int64, occurrence = required, opts = []},
     #field{name = openId, fnum = 2, rnum = 3, type = string,
	    occurrence = required, opts = []},
     #field{name = nickname, fnum = 3, rnum = 4,
	    type = string, occurrence = required, opts = []},
     #field{name = avatarUrl, fnum = 4, rnum = 5,
	    type = string, occurrence = required, opts = []},
     #field{name = isRobot, fnum = 5, rnum = 6, type = int32,
	    occurrence = required, opts = []},
     #field{name = gender, fnum = 6, rnum = 7, type = int32,
	    occurrence = required, opts = []},
     #field{name = battleTimes, fnum = 7, rnum = 8,
	    type = int32, occurrence = optional, opts = []},
     #field{name = robotLevel, fnum = 8, rnum = 9,
	    type = int32, occurrence = optional, opts = []}];
find_msg_def(sc_11003) ->
    [#field{name = readyTime, fnum = 1, rnum = 2,
	    type = int32, occurrence = required, opts = []},
     #field{name = playerInfos, fnum = 2, rnum = 3,
	    type = {msg, playerInfo}, occurrence = repeated,
	    opts = []}];
find_msg_def(cs_11010) ->
    [#field{name = processData, fnum = 1, rnum = 2,
	    type = bytes, occurrence = required, opts = []}];
find_msg_def(sc_11011) ->
    [#field{name = playerId, fnum = 1, rnum = 2,
	    type = int64, occurrence = required, opts = []},
     #field{name = playerScore, fnum = 2, rnum = 3,
	    type = int32, occurrence = required, opts = []},
     #field{name = resultData, fnum = 3, rnum = 4,
	    type = bytes, occurrence = required, opts = []},
     #field{name = seeds, fnum = 4, rnum = 5, type = int32,
	    occurrence = repeated, opts = []}];
find_msg_def(cs_11012) ->
    [#field{name = winPlayerId, fnum = 1, rnum = 2,
	    type = int64, occurrence = required, opts = []}];
find_msg_def(sc_11002) ->
    [#field{name = result, fnum = 1, rnum = 2, type = int32,
	    occurrence = required, opts = []},
     #field{name = playerId, fnum = 2, rnum = 3,
	    type = int64, occurrence = required, opts = []},
     #field{name = openId, fnum = 3, rnum = 4, type = string,
	    occurrence = required, opts = []},
     #field{name = seeds, fnum = 4, rnum = 5, type = int32,
	    occurrence = repeated, opts = []}];
find_msg_def(sc_11010) ->
    [#field{name = playerId, fnum = 1, rnum = 2,
	    type = int64, occurrence = required, opts = []},
     #field{name = processData, fnum = 2, rnum = 3,
	    type = bytes, occurrence = required, opts = []}];
find_msg_def(cs_11013) -> [];
find_msg_def(cs_11004) -> [];
find_msg_def(cs_11002) -> [];
find_msg_def(cs_11011) ->
    [#field{name = playerScore, fnum = 1, rnum = 2,
	    type = int32, occurrence = required, opts = []},
     #field{name = resultData, fnum = 2, rnum = 3,
	    type = bytes, occurrence = required, opts = []},
     #field{name = level, fnum = 3, rnum = 4, type = int32,
	    occurrence = optional, opts = []},
     #field{name = score2, fnum = 4, rnum = 5, type = int32,
	    occurrence = optional, opts = []}];
find_msg_def(_) -> error.


find_enum_def(_) -> error.


-spec enum_symbol_by_value(_, _) -> no_return().
enum_symbol_by_value(E, V) ->
    erlang:error({no_enum_defs, E, V}).


-spec enum_value_by_symbol(_, _) -> no_return().
enum_value_by_symbol(E, V) ->
    erlang:error({no_enum_defs, E, V}).



get_service_names() -> [].


get_service_def(_) -> error.


get_rpc_names(_) -> error.


find_rpc_def(_, _) -> error.



-spec fetch_rpc_def(_, _) -> no_return().
fetch_rpc_def(ServiceName, RpcName) ->
    erlang:error({no_such_rpc, ServiceName, RpcName}).


get_package_name() -> undefined.



gpb_version_as_string() ->
    "4.1.3".

gpb_version_as_list() ->
    [4,1,3].
