%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.3

-ifndef(p10).
-define(p10, true).

-define(p10_gpb_version, "4.1.3").

-ifndef('SC_10001_PB_H').
-define('SC_10001_PB_H', true).
-record(sc_10001,
        {result                 :: integer(),       % = 1, 32 bits
         roomId                 :: integer(),       % = 2, 32 bits
         matchId                :: iolist() | undefined % = 3
        }).
-endif.

-ifndef('CS_10000_PB_H').
-define('CS_10000_PB_H', true).
-record(cs_10000,
        {openId                 :: iolist(),        % = 1
         sign                   :: iolist(),        % = 2
         timestamp              :: integer(),       % = 3, 32 bits
         appId                  :: integer(),       % = 4, 32 bits
         params = []            :: [iolist()] | undefined % = 5
        }).
-endif.

-ifndef('SC_10010_PB_H').
-define('SC_10010_PB_H', true).
-record(sc_10010,
        {result                 :: integer(),       % = 1, 32 bits
         cpOrderId              :: iolist() | undefined, % = 2
         cpPropName             :: iolist() | undefined, % = 3
         cpPropId               :: iolist() | undefined, % = 4
         payAmount              :: integer() | undefined % = 5, 32 bits
        }).
-endif.

-ifndef('SC_10000_PB_H').
-define('SC_10000_PB_H', true).
-record(sc_10000,
        {result                 :: integer(),       % = 1, 32 bits
         playerId               :: integer(),       % = 2, 32 bits
         nickname               :: iolist() | undefined, % = 3
         avatarUrl              :: iolist() | undefined, % = 4
         openId                 :: iolist() | undefined % = 5
        }).
-endif.

-ifndef('CS_10010_PB_H').
-define('CS_10010_PB_H', true).
-record(cs_10010,
        {cpPropId               :: iolist()         % = 1
        }).
-endif.

-ifndef('CS_10011_PB_H').
-define('CS_10011_PB_H', true).
-record(cs_10011,
        {cpOrderId              :: iolist()         % = 1
        }).
-endif.

-ifndef('CS_10001_PB_H').
-define('CS_10001_PB_H', true).
-record(cs_10001,
        {gameMode               :: integer(),       % = 1, 32 bits
         matchType              :: integer(),       % = 2, 32 bits
         matchId                :: iolist() | undefined % = 3
        }).
-endif.

-ifndef('SC_10011_PB_H').
-define('SC_10011_PB_H', true).
-record(sc_10011,
        {result                 :: integer(),       % = 1, 32 bits
         cpOrderId              :: iolist()         % = 2
        }).
-endif.

-endif.
